### ISSUE TITLE
new release out?

### ISSUE THREAD

**Issue by sotaan** [icebob/vue-form-generator#10]
I see some changes in your code from github (breaked form layout, ...) but no new release out in the tags so npm refuse to fetch the last code. Is the new code trustable?
BTW thanks for this package and keep up the good work!

**Comment by icebob** [comment]
@sotaan I rewrite the layout (move label to top of the input). I didn't release new version because I will add some minor changes too.

**Comment by icebob** [comment]
Released v0.2.0
https://github.com/icebob/vue-form-generator/releases/tag/v0.2.0
