### ISSUE TITLE
How to use Bootstrap form classes?

### ISSUE THREAD

**Issue by thatcort** [icebob/vue-form-generator#106]
Hi,

How does one assign Bootstrap's form classes for layout? For example adding `class="form-horizontal"` to the enclosing div has no effect.

Thank you!

**Comment by icebob** [comment]
Add your classes to the `styleClasses` props of the schema.

**Comment by thatcort** [comment]
Thanks for the tip. Usinng `styleClasses` seems to wrap the whole field in a class. Is there a way to specify that the label gets `col-sm-2` and the input gets `col-sm-10`?

I have an unrelated question too: I was looking through the code and see you using `$get()` (i.e. `this.$get("model." + this.schema.model)` but can't find this method documented anywhere. Can you point me to a definition for it?

Thank you!

**Comment by icebob** [comment]
Sorry, but currently you can't set style class for the field, because the main class don't know that the fields have input element.

`this.$get` is a built-in VueJS method. [More info](http://v1.vuejs.org/api/#vm-get)

**Comment by thatcort** [comment]
Ah, $get() seems to be gone in 2.0. That explains why some of my models aren't working.
