### ISSUE TITLE
Remove deprecated fields

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#120]
In v2.x version we need to remove the deprecated fields. You can use the `input` field with `inputType` property  instead of them.

Deprecated fields:
- [x] **color**
	Change `{ type: "color" }` to `{ type: "input", inputType: "color" } `
- [x] **email**
	Change `{ type: "email" }` to `{ type: "input", inputType: "email" } `
- [x] **number**
	Change `{ type: "number" }` to `{ type: "input", inputType: "number" } `
- [x] **password**
	Change `{ type: "password" }` to `{ type: "input", inputType: "password" } `
- [x] **range**
	Change `{ type: "range" }` to `{ type: "input", inputType: "range" } `
- [x] **text**
	Change `{ type: "text" }` to `{ type: "input", inputType: "text" } `

- [ ] update docs & readme

**Comment by cristijora** [comment]
Nice. Will keep things more simple and clear

**Comment by lionel-bijaoui** [comment]
While I was moving fields around with #121, I also removed the designated fields.
