### ISSUE TITLE
Update docs & readme

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#123]
After #120 we need to update docs & readme

- **Update docs on gitbook**
  - [ ] rewrite examples
  - [ ] refresh "Install" & "Usage" section (how to use full & core bundle)
  - [ ] refresh "Features" section
  - [ ] add info about bundle sizes
  - [ ] refresh dependencies (remove momentjs)

---------------
- **Update readme**
  - [ ] rewrite examples
  - [ ] refresh "Install" & "Usage" section (how to use full & core bundle)
  - [ ] refresh "Features" section
  - [ ] add info about bundle sizes
  - [ ] refresh dependencies (remove momentjs)

**Comment by lionel-bijaoui** [comment]
I'm on it, but I don't think I will have the time to do everything

**Comment by icebob** [comment]
OK, I can help you!

**Comment by lionel-bijaoui** [comment]
Ok, I will inform you when I finished. Thank you !

**Comment by lionel-bijaoui** [comment]
I don't know how to handle the new hierarchy of fields.
Should we do something that show the need for dependency:
- build in (mixing core and optional field)
- optionnal
  - jquery
  - vanilla

OR
Should we show what's in core vs optional:
- core
- optionnal (mixing dependent and independent)

I'm more the second option, since we explicitly say which dependency have each field in its description.
What are your thought ?

**Comment by icebob** [comment]
I agree the second option.

**Comment by lionel-bijaoui** [comment]
I have added this into the custom field page
> if you decide to release your custom field into the wild, please open an issue so we can add you to a list on the README

I think we should encourage people to release their own custom field. Can we agree on a naming convention for vfg custom field ?
- `vue-form-generator-my-field`
- `vfg-my-field`
- `vfg-plugin-my-field`

That would allow people to find other custom field easily. What do you think about that ?

**Comment by icebob** [comment]
I prefer `vfg-my-field`.

`vue-form-generator....` is too long.
`vfg-plugin....` I think it is confuse, because it is not plugin. It is a field or component.

**Comment by icebob** [comment]
Or `vfg-field-mystuff`
E.g.:
`vfg-field-calendar`
`vfg-field-awesome-dropdown`

**Comment by lionel-bijaoui** [comment]
I like your proposition. It keep the current naming convention used internally.
We should mention this somewhere on the README to encourage people ! 😃

**Comment by lionel-bijaoui** [comment]
I just realized that I don't know how to use the core version.
```js
// the normal way
import VueFormGenerator from "vue-form-generator";
```
I'm really confuse as to how this is going to work
```js
// the "core" way ???
import VueFormGenerator from "vue-form-generator/dist/vue-form-generator-core.js";
```

**Comment by icebob** [comment]
The code is correct, but ugly :confused:

**Comment by icebob** [comment]
But this is the correct way. Like with Vue when you want to use the vue.common.js. [Vue solution](https://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build) is you need to create an alias in webpack config

**Comment by lionel-bijaoui** [comment]
Have you tested it ?
BTW, I think we should use an alias for the "utils" folder.

**Comment by lionel-bijaoui** [comment]
Also, we never mention how to use the css file.

**Comment by cristijora** [comment]
Why not rename this to `common.js` or `core.js` without having the whole `vue-form-generator...`
Once you try to import from the npm directory you know that it's the form generator.

**Comment by lionel-bijaoui** [comment]
Yeah, like `full.js` and `core.js`. I fear that `common.js` might get mixed up with CommonJS specific usage.
As for the CSS, I did that
````html
<style  src="../../dist/vue-form-generator-core.css"></style>
```
Good news is that it work, bad news is that it look bad with all the style on dev

**Comment by cristijora** [comment]
Yeah `full.js` and 'core.js` sounds fine. What do you mean it looks bad ?

**Comment by lionel-bijaoui** [comment]
@cristijora maybe an in-between with `vfg-core.js` and `vfg.js` ?
I mean that some element don't look the same when you include the css extracted from vfg

**Comment by cristijora** [comment]
Hm, actually yeah. I think that one is the best option so far.

**Comment by icebob** [comment]
Other solution is, we drop the dist folder and place bundles js & css to root of repo.
In this case the links look as:
```
import VueFormGenerator from "vue-form-generator/vfg-core.js";
import VueFormGenerator from "vue-form-generator/vfg-full.js";

import "vue-form-generator/vfg-core.css";
```

**Comment by icebob** [comment]
What is the problem with extracted CSS? I didn't find any problem. Please make a screenshot.

**Comment by lionel-bijaoui** [comment]
@icebob I think I'm finished with the doc. Not everything is done, so I let you take a look.

**Comment by icebob** [comment]
Sorry for late. I was ill. Thanks. I'll check it

**Comment by icebob** [comment]
I checked, I think it's correct. I fix some examples and make some minor changes.
I will update the README.

**Comment by icebob** [comment]
Done
