### ISSUE TITLE
Disable submit button

### ISSUE THREAD

**Issue by pimhooghiemstra** [icebob/vue-form-generator#128]
I am a bit stuck with the submit button of a form. I would like to disable the submit button when validation fails and enable it again once all fields pass validation.

However, according to the docs we can use the disabled property in the schema for any field and using it on a submit button adds a 'disabled' attribute to the HTML, but on the outer div.form-group. I expected it on the input[type=submit]...

My idea was to use the onValidated callback for an individual field to toggle this enabled/disabled state on the submit button.

Is something like this possible?

Here is a fiddle showing the issue: https://jsfiddle.net/pimhooghiemstra/0mg1v81e/207/

**Comment by icebob** [comment]
The `disabled` property can be function too.
Please try it:
```
{
              type:"submit",
              buttonText:"Click me to submit",
              onSubmit:this.submitForm,
              disabled() {
		return this.errors.length == 0;
   	     }
}
```

> or `this.$parent.errors.length` ?!?!

**Comment by icebob** [comment]
Hmm, not working because the `this` not binded to the instance of field.

**Comment by icebob** [comment]
I will fix it in the next release.

**Comment by pimhooghiemstra** [comment]
Great! I have a workaround for the moment but it quickly becomes ugly i am afraid.

**Comment by icebob** [comment]
@pimhooghiemstra the solution & fix is coming with #129

**Comment by icebob** [comment]
If you updated, could you try this solution?
```js
{
              type:"submit",
              buttonText:"Click me to submit",
              onSubmit:this.submitForm,
              disabled() {
		return this.$parent.errors.length != 0;
   	     }
}
```

**Comment by pimhooghiemstra** [comment]
I'll try this tomorrow

**Comment by pimhooghiemstra** [comment]
@icebob I copied the code above for the submit button, but unfortunately this gives me an error.
![screen shot 2017-02-23 at 10 40 07](https://cloud.githubusercontent.com/assets/7228111/23253376/8e544456-f9b4-11e6-8f35-d244301a42b1.png)

If I check the Vue devtools, it doesn't seem there is a parent errors object?

![screen shot 2017-02-23 at 10 43 30](https://cloud.githubusercontent.com/assets/7228111/23253476/f6b7574a-f9b4-11e6-921b-6e68647151ee.png)


Then I tried the disabled() function to just return true, thinking the button would be disabled on page load but that was not the case.

Maybe I am missing something?

**Comment by icebob** [comment]
Yes, there are some other bugs :) I doing a hotfix.

**Comment by icebob** [comment]
Done.

So, the first problem is, that the `this` is not the field instance, it is the vfg instance. So you have to use `this.errors.length > 0`.

Other problem, `fieldSubmit` hadn't disabled attribute, I fixed. 
Last problem, there was no any CSS style for disabled button, fixed.

Firstly, run `npm install icebob/vue-form-generator` to update the last files.
Use this code in your schema:
```js
{
	type: "submit",
	label: "",
	buttonText: "Submit form",
	onSubmit(model, schema) {
		alert("Form submitted!");
	},
	disabled() {
		return this.errors.length > 0;
	}
}
```

I hope it'll work for you.

**Comment by icebob** [comment]
@pimhooghiemstra Working?

**Comment by pimhooghiemstra** [comment]
@icebob I had a quick (maybe too quick) look last week and it did not work. However, I'll try again today and will post my results later today. Excuse me for the delay.

**Comment by pimhooghiemstra** [comment]
@icebob I had a more rigorous look and now it works indeed, thanks!

What took me by surprise is the fact that the styling of the disabled submit button is not different from the not-disabled version, this makes the button clickable even when disabled. 

Maybe this would be better
`fieldset.vue-form-generator .field-wrap input[type=submit]:disabled {
    cursor: not-allowed;
    opacity: 0.65;
}`

Anyway, I am happy it works now

**Comment by icebob** [comment]
I added  the same css style to form generator when fixed the issue: https://github.com/icebob/vue-form-generator/blob/master/src/formGenerator.vue#L405

I'm glad it is working. I will make a new beta release in a short time.

**Comment by icebob** [comment]
[New beta released](https://github.com/icebob/vue-form-generator/releases/tag/v2.0.0-beta5)
