### ISSUE TITLE
datetime-local input bug

### ISSUE THREAD

**Issue by lkho** [icebob/vue-form-generator#130]
## Bug
fieldInput.vue
```javascript
			formatValueToModel(value) {
				if (value != null) {
					if (this.schema.inputType === "date" ||
						this.schema.inputType === "datetime" ||
						this.schema.inputType === "datetimelocal") {
						return new Date(value).getTime();
					}
				}
				
				return value;
			}
```
`datetimelocal` is incorrectshould be `datetime-local`

Also, I found that `new Date(value)` in chrome will treat the value as UTC if it has a 'T', but instead it is 'local without timezone', so the value returned will be wrong. don't know if other browsers would do the same: https://jsfiddle.net/setn3460/

So I suggest using Moment as it returns consistent values

**Comment by icebob** [comment]
Thanks. We won't change to using moment because we removed recently to decrease the bundle size.

**Comment by lkho** [comment]
then maybe we can parse that using another method such as regex as the format returned is stated in w3c thus i think it will not change?

**Comment by icebob** [comment]
Thanks!

**Comment by icebob** [comment]
[Released your fix in beta5](https://github.com/icebob/vue-form-generator/releases/tag/v2.0.0-beta5)
