### ISSUE TITLE
type: 'cleave' allows extraneous input

### ISSUE THREAD

**Issue by voughtdq** [icebob/vue-form-generator#131]
Given the following component:

```
<template>
  <div>
    <vue-form-generator :schema="schema" :model="model" :options="options"></vue-form-generator>
    {{ model }}
  </div>
</template>

<script>
import Vue from 'vue'
import VueFormGenerator from 'vue-form-generator'
Vue.use(VueFormGenerator)

export default {
  data () {
    model: {
      dob: ''
    },
    schema: {
      fields: [{
        type: 'cleave',
        label: 'Date of birth',
        model: 'dob',
        cleaveOptions: {
          date: true,
          datePattern: ['d', 'm', 'Y'],
          delimiter: '/'
        }
      }]
    }
  }
}
</script>

```

The model will erroneously accept an additional character at the end of input. The model will be updated in Vue, but the change isn't shown within the actual input element.

For example, the above component will allow me to enter: `030420011`. The value in the model will be `03/04/20011`, BUT the value in the actual field will be `03/04/2001`. 

If I backspace, the value in the model is reduced by 2 characters with the value in the actual field being reduced to 1.

![cleave_bug](https://cloud.githubusercontent.com/assets/1967287/23340672/66ea013e-fc08-11e6-8c57-61597df4e7ba.png)

**Comment by voughtdq** [comment]
Sorry. I need to check if this is fixed in the dev version. I will close for now.

**Comment by voughtdq** [comment]
On version 2.0.0-beta4

**Comment by voughtdq** [comment]
Here is a better visualization of what is happening:
![bug](https://cloud.githubusercontent.com/assets/1967287/23341365/1f8bd748-fc14-11e6-8ced-91ea9be79761.gif)

**Comment by voughtdq** [comment]
I can also confirm that the cleave object itself has the correct data (see `$vm0.cleave.getFormattedValue()` and `$vm0.cleave.getRawValue()` both return the value without the extraneous character). 

I'll be back if I have any more info to report and hopefully a fix.

**Comment by lionel-bijaoui** [comment]
Thanks a lot for your help !

**Comment by voughtdq** [comment]
I spent way too much time trying to debug this. I still found a solution, just not one that is as elegant as I'd like. I resolved this by adding `onChanged` to my schema:

```
... {
  type: 'cleave',
  label: 'Date of birth',
  model: 'dob',
  cleaveOptions: {
    date: true,
    datePattern: ['d', 'm', 'Y'],
    delimiter: '/'
  },
  onChanged (model, newVal, oldVal, field) {
    if (model[field.model].length >= 11) {
      model[field.model] = oldVal
  }
} ...
```

Very useful. I'm glad the functionality is there!

**Comment by icebob** [comment]
Thanks @voughtdq . Please don't close because it is a bug. We will try to fix it.

**Comment by voughtdq** [comment]
There is a vue-cleave library that gives some insight - it looks like cleave.js relies on the max length property to guard against extraneous input. I will look into this around 04:30 UTC

**Comment by pjaer** [comment]
Anybody had any luck with this? I believe it is still around, as I'm experiencing it. Thanks

**Comment by lionel-bijaoui** [comment]
@voughtdq Can you please give us an update about this ? Did you managed to fix this ? If yes, how ? Thanks !

**Comment by voughtdq** [comment]
I never figured it out - sorry :(

**Comment by pjaer** [comment]
I updated to the latest vue-cleave and it solved it for me, except on mobile chrome.. there it still doesn't work

**Comment by icebob** [comment]
Fixed by @hansi90
