### ISSUE TITLE
How to translate validator messages?

### ISSUE THREAD

**Issue by gkurdej** [icebob/vue-form-generator#134]
How can I translate built-in validator messages? Is it possible? I need it in Polish...

**Comment by icebob** [comment]
Yes, it is possible. You need to overwrite the [resources props](https://github.com/icebob/vue-form-generator/blob/master/src/utils/validators.js#L22) in validators.

```js
		created() {
			var res = VueFormGenerator.validators.resources;
			res.textTooSmall = "Túl rövid a szöveg!"
		}
```

[Example fiddle](https://jsfiddle.net/icebob/0mg1v81e/242/)
> if you delete the password you will see the custom validator message

**Comment by gkurdej** [comment]
I did something like this yesterday and it was working, when I did it at the component level, but I don't know how to setup it once for the whole app (I have few forms in my app). This code should be placed at the created() method of the main App.vue component?

**Comment by icebob** [comment]
You can place this code everywhere after vfg imported. E.g. App.vue created or mounted. [Example](https://github.com/icebob/vue-form-generator/blob/master/dev/full/app.vue#L212)

**Comment by gkurdej** [comment]
Translations are working fine, thanks!

Now I have an issue with number validators :( Validators (nubmer, integer, double) uses lodash isNumber function, which evaluates to false if argument is type of string. Maybe I'm wrong, but value, which is returned from input is type of string and should be converted to number before validation? I tested it with field type='input' and inputType='number' / 'integer' / 'double' and always get 'Invalid number!'
https://lodash.com/docs/4.17.4#isNumber

**Comment by icebob** [comment]
@gkurdej please open a new issue about it and if you can please create a jsfiddle.
