### ISSUE TITLE
Should `vue` be a `devDependencies` instead of a `dependency` ?

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#135]
When I install VFG for my project, I realized that a different version of `vue` was installed. I guess npm does that because it it listed under `dependencies` in `package.json`.
But this is useless, no ?
If I want to clone the project to work on it, I will install `dependency` and `devDependencies`.
However, if I want to use VFG as a plugin/component, I don't need to install this specific version of `vue`.
I can do:
```
import {component} from 'vue-form-generator';

export default {
    components: {
        'vue-form-generator': component
    }
}
```
As long as I use vue 2 it should work

**Comment by icebob** [comment]
Yes, it can be devDep. Could you make a PR?

**Comment by lionel-bijaoui** [comment]
Yes, will do.

-----
I was also wondering about src/index.js.

When VFG is used as a plugin with vue-loader, it should load the `.vue` file not the compiled `.js` files. the compiled `.js` is usefull for the CDN or people that want to install manually the lib.

https://vuejs.org/v2/guide/plugins.html
https://alligator.io/vuejs/creating-custom-plugins/
https://github.com/JosephusPaye/Keen-UI/blob/master/src/index.js

`schema`, `validators` and `abstractField` could live under `this.$vfg`.
We could add this for automatic install:
```
if (typeof window !== 'undefined' && window.Vue) {
    window.Vue.use(VFG);
}
```
Should I make another PR for this or is there a reason for this situation ?

**Comment by icebob** [comment]
I don't understand it. I think you have to use the compiled dist js when you are using as a plugin.

**Comment by lionel-bijaoui** [comment]
Are you sure ? From reading the documentation and the article, it seem like you could use the sources directly. Pretty much what we do with the dev environment but in production:
```js
// from dev/full/app.vue
import VueFormGenerator from "../../src";
Vue.use(VueFormGenerator);

// default way to use vfg in another project
import VueFormGenerator from "vue-form-generator";
// use compiled js from dist/vfg.js
Vue.use(VueFormGenerator);

// my proposal
import VueFormGenerator from "vue-form-generator/src";
// use source file (.vue files) and compile them along the rest of the project with webpack
// that would necessitate to have "pug-loader" and other plugin since this is an advance use
Vue.use(VueFormGenerator);
```
I'm sorry if this don't make any sense or is impossible, but again, from the documentation and these article, I feel like it could be done.

**Comment by cristijora** [comment]
Hey guys why not get rid of babel-runtime and vue from devDependencies. Why not writing simple html instead of pug ? This will make the proposed thing from @lionel-bijaoui possible without the users needing to install any extra stuff.

**Comment by lionel-bijaoui** [comment]
I'm going to test everything and test with my fork on my project to see if it is possible/working.
Removing pug will be long so I will not do it right now.
I keep you updated on my progress!

**Comment by lionel-bijaoui** [comment]
So far i'm hitting a brickwall.
So I had to change the config and change 'sass' to 'scss', and some other tweak.

The bundling work without error, but the navigator fail. Webpack don't seem to transpile with babel (I tried to include the path to the loader config). so every 'import something from './here' is keep as is and it cause problems. Webpack 2 seem to be able to fix that but my project is made with webpack 1 so I'm not going to change everything.


@cristijora I encourage you to take a look at my branch, I hope you can succeed: https://github.com/lionel-bijaoui/vue-form-generator/tree/lb_alternative_plugin_behavior

**Comment by lionel-bijaoui** [comment]
Sorry, I forgot to do the PR, but here it is.
