### ISSUE TITLE
Number validations

### ISSUE THREAD

**Issue by gkurdej** [icebob/vue-form-generator#137]
I have an issue with number validators. 
Input type="input", inputType="number" - validation always fails with message "Invalid number".
Here is example fiddle - try to enter number in Age field:
https://jsfiddle.net/o6tfzccs/1/

Validators (nubmer, integer, double) uses lodash isNumber function, which evaluates to false if argument is type of string. Maybe I'm wrong, but value, which is returned from input is type of string and should be converted to number before validation? 
https://lodash.com/docs/4.17.4#isNumber

**Comment by cristijora** [comment]
That seems to be a bug. I guess it's pretty easy to fix.

**Comment by icebob** [comment]
I'm on it.

**Comment by icebob** [comment]
[New beta released with this fix](https://github.com/icebob/vue-form-generator/releases/tag/v2.0.0-beta5)

**Comment by gkurdej** [comment]
Test passed. Good job :)
