### ISSUE TITLE
Problem with inputType="date"

### ISSUE THREAD

**Issue by gkurdej** [icebob/vue-form-generator#138]
I have problem with field type="input", inputType="date" and inputType="datetime-local"
This fields save date in format: Fri Nov 30 1973 00:00:00 GMT+0100 (CET)
But cannot read such format. I expects number: 123412323232

Fiddle:
https://jsfiddle.net/ebmgv286/3/

**Comment by icebob** [comment]
Thanks, [missing some formatter](https://github.com/icebob/vue-form-generator/blob/master/src/utils/dateFieldHelper.js) from field code

**Comment by icebob** [comment]
Hot fix: https://jsfiddle.net/icebob/ebmgv286/4/

```js
{
	type: "input",
	inputType: "date",
	label: "Example date",
	model: "exampleDate",
	set: function(model, val) {
		model.exampleDate = new Date(val).valueOf();
	}
}
```

**Comment by gkurdej** [comment]
I checked fiddle - now I can save and read dates without errors. Much better :)

Is it possible to save dates in other format? E.g. "2017-03-02 12:04:00"?

**Comment by icebob** [comment]
If I fixed this bug in vfg then yes.

**Comment by icebob** [comment]
I fixed it. Fiddle with the fixed bundle: https://jsfiddle.net/ebmgv286/5/

**Comment by dflock** [comment]
Does this require any docs changes?

**Comment by icebob** [comment]
@dflock Maybe. Because now `type="input"` field have a "format" property if the `inputType` is `date`, ˛`datetime` or `datetime-local`

**Comment by brunofullstack** [comment]
> Hot fix: https://jsfiddle.net/icebob/ebmgv286/4/
> 
> ```js
> {
> 	type: "input",
> 	inputType: "date",
> 	label: "Example date",
> 	model: "exampleDate",
> 	set: function(model, val) {
> 		model.exampleDate = new Date(val).valueOf();
> 	}
> }
> ```
This work for me. Thanks!
