### ISSUE TITLE
Checklist doesn't trigger event at each value change

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#142]
From #140 
>I found a bug on checklist, it don't update the model except the first time. So I listen to model-updated on vfg:
>-  radios change at every click, and trigger a model-updated event.
>-  checklist change at the first change, but after that, if I uncheck the checkbox, or if I check another one, nothing get triggered in model-updated.

I think I found the problem. The `onChanged` method is triggered by listening to the `change` event. If you read the documentation about it (from [MDN](https://developer.mozilla.org/en-US/docs/Web/Events/change))
>The change event is fired for `<input>`, `<select>`, and `<textarea>` elements when a change to the element's value is committed by the user. **Unlike the input event, the change event is not necessarily fired for each change to an element's value.**

I will do a PR where I modify the type of event listened to (from `change` to `input`).

**Comment by lionel-bijaoui** [comment]
`checklist` input event doesn't fire as it should in chrome and safari.
There is a bug right now in [chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=534245) and [safari](https://bugs.webkit.org/show_bug.cgi?id=149398) with [input event](http://caniuse.com/#feat=input-event).
The change event doesn't fire each time (by design), the input event doesn't fire each time (by bug), the click and keyup/keydown event fire each time but break the logic in the `onChanged` method and end up triggering only once.
I don't know how to fix that.

**Comment by NGorco** [comment]
With that build https://unpkg.com/vue-form-generator@2.0.0-beta5 we have working checklist.

**Comment by icebob** [comment]
@NGorco thanks for this information!

**Comment by icebob** [comment]
@lionel-bijaoui when doesn't fired the `change` event? I'm trying in Chrome and it works properly.

**Comment by lionel-bijaoui** [comment]
When you click multiple times on a `checklist` item. Maybe they fixed it in the latest release ?
I have tested it and it work without problem with `change` event. I need to revert my changes. FML 😢 
Sorry everyone...

**Comment by icebob** [comment]
I don't have found problem with it. I reverted in checklist field.
