### ISSUE TITLE
Bug: Number (double) validator

### ISSUE THREAD

**Issue by lkho** [icebob/vue-form-generator#144]
https://github.com/icebob/vue-form-generator/blob/cef504df01c539a39e2966ce93b94890a5cfcc6f/src/utils/validators.js#L88

An integer should be a valid double value.

**Comment by lionel-bijaoui** [comment]
@lkho Can you maybe provide a PR ? Thanks

**Comment by icebob** [comment]
But after it, I don't know what is the difference between `number` and `double`.
