### ISSUE TITLE
Default values are not working

### ISSUE THREAD

**Issue by reardestani** [icebob/vue-form-generator#147]
Hi,

I forked the official example and removed the model values to see if default values are working or not and it seems they are not working. Am I missing something?

https://jsfiddle.net/reardestani/caqcyagh/2/

**Comment by icebob** [comment]
vfg is not used the default values directly. 
If you want to create a new model you have to call the "createDefaultObject" function with schema. And it will create a new object with the default values of the schema.

I updated your fiddle with the "new" button: https://jsfiddle.net/icebob/caqcyagh/3/

```js
newModel() {
	this.model = VueFormGenerator.schema.createDefaultObject(this.schema);
}
```

**Comment by reardestani** [comment]
Thanks it works great.
