### ISSUE TITLE
localization validator

### ISSUE THREAD

**Issue by wormen** [icebob/vue-form-generator#15]
How can I transfer localization for a validator in the component?

**Comment by icebob** [comment]
Currently you can't. I will add resources to validator

**Comment by wormen** [comment]
and when it will be?

**Comment by icebob** [comment]
Some days

**Comment by icebob** [comment]
Can be change validation error messages:
```js
			// Localize validate errors
			VueFormGenerator.validators.resources.fieldIsRequired = "Ezt a mezőt kötelező kitölteni!";
			VueFormGenerator.validators.resources.textTooSmall = "A szöveg túl rövid! Jelenleg: {0}, minimum: {1}";
```

**Comment by wormen** [comment]
using your example, I got error
`
Uncaught TypeError: Cannot set property 'fieldIsRequired' of undefined
`

here is the code
```
VueFormGenerator.validators.resources.fieldIsRequired = "Полу обязательно для заполнения!";
```

**Comment by CorentinN** [comment]
I manage to modify the error messages lie this 
`validators.resources.fieldIsRequired= "Your new error message";`
