### ISSUE TITLE
Accessing model-updated event

### ISSUE THREAD

**Issue by reardestani** [icebob/vue-form-generator#158]
Hi, 

I am not sure why I can't access the model-updated event in my custom components. I can access the **Root** events but not to **VueFormGenerator** ones. It seems I am missing a point.

https://jsfiddle.net/reardestani/0mg1v81e/261/

### Expectation
If a user click on **color input**, both of events should be run not only global one. 

Thanks in advance,

**Comment by cristijora** [comment]
It works just fine for me. I get the `model-event` logged in console whenever I change the input values.

**Comment by reardestani** [comment]
Yes, you're right. It seems I had issue in the main script. Thanks for checking.
