### ISSUE TITLE
image type - display selected filename

### ISSUE THREAD

**Issue by MaksimSkomorokh** [icebob/vue-form-generator#17]
At once image selected on localhost text/placeholder of input changing to <inline base64 image>
Is possible to hide input with filename or just show filename?
https://jsfiddle.net/0mg1v81e/10/

**Comment by icebob** [comment]
Ok, I added a property which can hide the input field after browse.

**Comment by icebob** [comment]
It's working properly, just need to initialize the image property in data
```js
        model: {
            id: 1,
            name: "John Doe",
            password: "J0hnD03!x4",
            skills: ["Javascript", "VueJS"],
            email: "john.doe@gmail.com",
            logo: null,
            status: true
        },
```
https://jsfiddle.net/icebob/0mg1v81e/20/
