### ISSUE TITLE
How to figure out if entire form is valid or invalid?

### ISSUE THREAD

**Issue by phredeye** [icebob/vue-form-generator#177]
I see in the documentation that there is a way to react to validation events on individual fields, but lets say I wanted to disable a submit button until the form is valid and the model ready for posting to an API.  What is the best way to go about that?  How can an external component have visibility into the current overall state of the form?

**Comment by cristijora** [comment]
You can use the `validated` event which is sent each time the fields are validated.
If you use form settings to validate after changes
```js
formOptions: {
            validateAfterLoad: true,
            validateAfterChanged: true
        }
```

The the `validated event will be sent each time an input changes
`this.$emit("validated", isValid, this.errors);`
You can handle this by simply having a function handler for the emitted event.
`<vue-form-generator :schema="schema" :model="model" :options="formOptions" @validated="handleValidation"></vue-form-generator>`
```js
handleValidation:function(isValid,errors){
         //logic to disable your submit button
   },
```

See [fiddle](https://jsfiddle.net/0mg1v81e/329/)

**Comment by jezmck** [comment]
Is there a way to have the submit button defined in the `schema` and be able to check that same `isSubmitDisabled` flag?

**Comment by zoul0813** [comment]
Jezmck - I don’t understand your question.

isSubmitDisabled is not a flag in VFG?

Please open a new issue if you are filing a bug report or feature request.

**Comment by jezmck** [comment]
`isSubmitDisabled` is a custom Vue data attribute in the linked fiddle.

**Comment by zoul0813** [comment]
"data" would need to be a function, and you can reference "this.isSubmitDisabled" using the submit's "disabled" property with a function ... 

Here's a Fiddle showing this in action - https://jsfiddle.net/72twpvmk/2/

**Comment by lahiponeja** [comment]
Hi,

Anyone can help me,  I need a example to code to event on option selectAll
in a checklist type with vue-form-generator.

Best Regards

**Comment by jezmck** [comment]
@lahiponeja You need to [open a new issue](https://github.com/vue-generators/vue-form-generator/issues/new).

**Comment by lahiponeja** [comment]
Ok, please sorry. I SOLVED
