### ISSUE TITLE
Handle errors provided by the backend app

### ISSUE THREAD

**Issue by andrzejkala** [icebob/vue-form-generator#181]
After passing all the validation requirements of `vfg`, the data is sent to the backend (as an `ajax` request) and sometimes the request returns an error.

e.g. a username or email is already taken.

I have a proper error message, have the name of the field, just can't find a way to "invalidate" this field. It doesn't have to be a proper invalidation, just need to somehow highlight the field and display the error message.

Is there some proper way to access a given input inside `vfg`?

**Comment by cristijora** [comment]
I don't know if you have any way of accessing specific fields but you can use async validators which were implemented [recently](https://github.com/icebob/vue-form-generator/releases/tag/v2.0.0-beta6)
but those are field specific as far as I know.

**Comment by andrzejkala** [comment]
Thanks @cristijora works like a charm! :)
