### ISSUE TITLE
inputType `date` not working

### ISSUE THREAD

**Issue by kevindessely** [icebob/vue-form-generator#184]
Error: `Unknown custom element: <field-date> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Weird that this this [JSFiddle](https://jsfiddle.net/icebob/ebmgv286/4/) works flawlessly, while mine doesnt.

I have tried setting vue-form-generator through, all three method does not work as well.
`Vue.use(VueFormGenerator)`
`{ components: VueFormGenerator }`
`Vue.component('vue-form-generator', VueFormGenerator.component);`

And tried [Tree View Example](https://vuejs.org/v2/examples/tree-view.html) doesn't work too.

I am using it inside a modal from `vue-bootstrap-modal@0.1.13` with `vue-form-generator@2.0.0-beta6`. Any help is appreciated, thank you.

Schema:
```
schema: {
  fields: [
    {
      type: "date",
      inputType: "date",
      label: "Date of Birth",
      required: true,
    }
  ]
},
```

**Comment by icebob** [comment]
The `type: "date"` is not available. You have to use `type: "input"` and `inputType: "date"`

**Comment by kevindessely** [comment]
Whoopps.. my bad, thank you @icebob !
