### ISSUE TITLE
load schema from server

### ISSUE THREAD

**Issue by jamesdixon** [icebob/vue-form-generator#185]
Hi again, is there a good way to load the schema from a server? We're using this to build a customizable form that can be embedded on any site. New to Vue and not sure how to defer loading of the component until the schema is available.

Thanks!

**Comment by cristijora** [comment]
So you want to prevent showing the component until you get the schema from server?

**Comment by jamesdixon** [comment]
@cristijora correct!

**Comment by cristijora** [comment]
If you use vue router you can prevent a route from loading until you tell it tohttp://router.vuejs.org/en/advanced/data-fetching.html

**Comment by jamesdixon** [comment]
We're trying to keep this as light weight as possible given this is an embeddable widget. Is there a way to do it without the router?

**Comment by cristijora** [comment]
Show a loading animation until you get the data from server. Other than the vue router option to really prevent data I don't know any way of doing it. Maybe load the schema in the parent component and render the widget only when data is present
