### ISSUE TITLE
hide label in form-group

### ISSUE THREAD

**Issue by cukikt0302** [icebob/vue-form-generator#187]
How to hide label element in from group?
It make whitespace row on button, checkbox,... 
in this image ...

**WHITESPACE**
![before](https://cloud.githubusercontent.com/assets/26678541/25579349/4fff8a68-2ea1-11e7-89d9-80b7e0685d24.PNG)
**REMOVE IT**
![after](https://cloud.githubusercontent.com/assets/26678541/25579348/4ff6efe8-2ea1-11e7-967d-bbf08c982a09.PNG)

**Comment by lionel-bijaoui** [comment]
```css
label:empty {
    display: none;
}
```
