### ISSUE TITLE
Cannot compile using gulp & Laravel

### ISSUE THREAD

**Issue by vladimir-yuldashev** [icebob/vue-form-generator#19]
[12:50:41] gulp-notify: [Laravel Elixir] Browserify Failed!: Cannot find module '!!./../../node_modules/css-loader/index.js!./../../node_modules/vue-loader/lib/style-rewriter.js?id=_v-c65c5786&scoped=true!./../../node_modules/sass-loader/index.js!./../../node_modules/vue-loader/lib/selector.js?type=style&index=0!./fieldCheckbox.vue' from '/node_modules/vue-form-generator/dist'

**Comment by icebob** [comment]
Could you give sample code?

**Comment by vladimir-yuldashev** [comment]
In package.json:

`"vue-form-generator": "^0.3.0"`

Create.Vue:

```
<template>
    <div>

        <section class="content-header">
            <h1>Create new entity</h1>
        </section>

        <section class="content">
            <vue-form-generator :schema="schema" :model="model" :options="formOptions"></vue-form-generator>
        </section>

    </div>
</template>

<script>

    import VueFormGenerator from "vue-form-generator";

    Vue.use(VueFormGenerator);

    export default {
        data() {
            return {
                schema: {
                    fields: [
                        {
                            type: "text",
                            label: "Name",
                            model: "name"
                        }
                    ]
                },
                model: {},
                formOptions: {
                    validateAfterLoad: false,
                    validateAfterChanged: true
                }
            }
        }
    }

</script>
```

**Comment by icebob** [comment]
Please show gulp task too. I see there is a problem with browserify

**Comment by vladimir-yuldashev** [comment]
It's standard Laravel Elixir task. 

`mix.browserify('app.js');`

**Comment by tvmota** [comment]
I have the same issue to implement in my project, using also laravel elixir

**Comment by icebob** [comment]
I need some help, because I have neved tried Laravel.

**Comment by blackfyre** [comment]
Another setup, but the same problem.

```javascript
import Vue from 'vue';
import VueFromGenerator from 'vue-form-generator';

Vue.use(VueFromGenerator.component);


window.gallery = new Vue({
  el: '#gallery',
  data: {
    templates: (()=>{
      return JSON.parse($('#templates').text());
    })()
  }
});
```

The runner is laravel/elixir 6.0.0-10 with the `mix.browserify('')` command.

**Comment by icebob** [comment]
@blackfyre OK, thanks, I will try to reproduce

**Comment by blackfyre** [comment]
@icebob Changing the packager to `webpack` works as intended, but many people use `browserify` or `rollup`. Sadly `rollup` is broken on my windows instance, so I cannot test that.

**Comment by icebob** [comment]
@blackfyre Could you try with this import?
```js
import VueFromGenerator from 'vue-form-generator/dist/vue-form-generator.min';
```

**Comment by blackfyre** [comment]
It works, at least there weren't any errors during the packaging process.

**Comment by icebob** [comment]
Good news. I think the problem is that the bundle file in dist folder contains some death code (`vue-loader` place it into bundle). But this part contains `require` what browserify try to resolve.

For example in line 116:
```js
	if (false) {(function () {  module.hot.accept()
	  var hotAPI = require("vue-hot-reload-api")
.....
```
And in the minimized file the `UglifyJS` plugin remove this parts.

**Comment by icebob** [comment]
In the next release the minimized version will be the default bundle file.

**Comment by blackfyre** [comment]
I don't think that would be a good idea... Packagers could distort the code even more, and it's generally discouraged to include already minified code into the build process...
