### ISSUE TITLE
请问是不是 inputType 这个属性已经不用了

### ISSUE THREAD

**Issue by blackhuman** [icebob/vue-form-generator#191]
我看[这篇文章](https://icebob.gitbooks.io/vueformgenerator/content/fields/field_properties.html) 的列表里没有 inputType 这个字段，几个 jsfiddle 上的例子也没有这个字段，请问这个字段是不是已经不用了？

**Comment by icebob** [comment]
English please!

**Comment by blackhuman** [comment]
#192
