### ISSUE TITLE
Is that the property inputType has been deprecated?

### ISSUE THREAD

**Issue by blackhuman** [icebob/vue-form-generator#192]
I found that the property "inputType" was not mentioned in the [post](https://icebob.gitbooks.io/vueformgenerator/content/fields/field_properties.html), neither can I found examples which use "inputType" property in jsfiddle. 

Is that the property inputType has been deprecated?

**Comment by lionel-bijaoui** [comment]
`inputType` is only for field of type `input`
```js
{
    'type': 'input',
    'inputType': 'text',
    'label': 'Your name :',
    'model': 'name',
    'placeholder': 'Jane Doe',
    'required': true
}
```

**Comment by blackhuman** [comment]
THX, i got it.
