### ISSUE TITLE
Update documentation for vue-multiselect 'trackBy'

### ISSUE THREAD

**Issue by navjeetfgmnt** [icebob/vue-form-generator#193]
As it states in vue-multiselect documentation it is a breaking change
**The :key props has changed to :track-by, due to conflicts with Vue 2.0.**
It causes select-options like 'hideSelected' and 'selectedLabel' to not work properly if using 'key' instead of 'trackBy'.
In the vueMultiSelect tab in documentation it still shows 'key' as a property [https://icebob.gitbooks.io/vueformgenerator/content/fields/vuemultiselect.html](url)

**Comment by icebob** [comment]
@lionel-bijaoui could you also fix it, please?
