### ISSUE TITLE
Is fieldset required for VFG ?

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#197]
Since VFG is using a `<fieldset>` as main tag, it is [impossible to use flexbox on it](http://stackoverflow.com/questions/28078681/why-cant-fieldset-be-flex-containers).
Flexbox allow for great layout to be made without any CSS hacks.
Knowing that most behaviors of forms are dealt with through use of JavaScript, can we simply use a div as a "wrapper" for the fields ?
Would that break something essential that I'm missing to see ?

**Comment by lionel-bijaoui** [comment]
I have a first solution to make it a little more flexible with the `is` attribute.
```html
// vfg.vue
<template>
    <div :is="tag">VFG</div>
</template>

<script>
export default {
    props: {
        tag: {
            type: String,
            default: 'fieldset'
        }
    }
};
</script>
```

```html
basic usage
<vfg></vfg>
config usage
<vfg tag="section"></vfg>
```

```html
basic usage rendered
<fieldset>VFG</fieldset>
config usage rendered
<section>VFG</section>
```

**Comment by DelfsEngineering** [comment]
Can we revisit this? flexbox is the jam and we simply can't use it because we cant attach a class to the field wrapper. We really need to be able to add classes or better, remove the `fieldset` wrapper completly.

**Comment by zoul0813** [comment]
@DelfsEngineering check formGenerator.vue

There’s a “tag” property you can assign to field groups, just use the field groups feature and you can also use the field group classes logic as well.
