### ISSUE TITLE
how to use methods from vue-form-generator button?

### ISSUE THREAD

**Issue by jackbbhua** [icebob/vue-form-generator#199]
anyway to fire vue methods from inside button?
Function(model, field) the model and field can not access to $parent or $root.can not access any top level data or methods for now.
thank you.

**Comment by icebob** [comment]
Good point. I will add instance of vfg to the button onclick handler as `this` & 3rd parameter.

**Comment by icebob** [comment]
Implemented. Example:
https://github.com/icebob/vue-form-generator/blob/master/dev/full/schema.js#L354
https://github.com/icebob/vue-form-generator/blob/master/dev/full/app.vue#L201

**Comment by jackbbhua** [comment]
hi icebob,it is still can not access this.$parent or this.i put methods at like this.$parent.$parent.$parent.

**Comment by icebob** [comment]
Sorry, I forgot to build :)
Please try now after `npm install icebob/vue-form-generator`

**Comment by jackbbhua** [comment]
it works good now.thank you icebob

**Comment by icebob** [comment]
Good. You're welcome.

**Comment by illcrx** [comment]
Those links posted above no longer work, is there anyway to rebuild them?

**Comment by zoul0813** [comment]
https://vue-generators.gitbook.io/vue-generators/fields/field_properties/inside_buttons

Use an arrow function < () = {} > to access the local Vue methods of the component

**Comment by illcrx** [comment]
I went through that and I am missing something, I have one large grouped form, where would I put those buttons? I tried 3 different places and I don't see anywhere in the docs or examples where buttons are placed in a group situation. Why are buttons omitted in so much example code, seems odd for forms?

**Comment by zoul0813** [comment]
Per the docs, and examples on that page, those buttons are attached to specific fields.

You can also create input buttons, such as submit, reset, etc as additional fields using the input field.

Your questions seem unrelated to this issue, if you need further assistance please try StackOverflow (for support), or open a new issue to report a bug or request features.
