### ISSUE TITLE
remove scoped styles

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#20]
- [x] Extract styles to a `vue-form-generator.css` file. #27
- [X] remove `scoped` from styles
- [x] create fiddle with an alternate style
- [X] Update examples, fiddle
- [x] Update docs

**Comment by icebob** [comment]
@lionel-bijaoui so we need to remove `scoped` from styles and use the extractTextPlugin in webpack to extract styles.

**Comment by lionel-bijaoui** [comment]
I can base myself on the [webpack vue-cli template](https://github.com/vuejs-templates/webpack).

**Comment by icebob** [comment]
This code is from my other project where I'm using ExtractTextPlugin for sccs extraction:
https://gist.github.com/icebob/b7ebfe9ca4494b380fb3fe2442e97f7f

**Comment by lionel-bijaoui** [comment]
extraction done

**Comment by icebob** [comment]
in Vue you need to import as a npm js module from node_modules... (I think :) )
```js
import style from "vue-form-generator/dist/vue-form-generator.css"
```

**Comment by lionel-bijaoui** [comment]
Ok, I don't have anything else to do on the files then. I found a way to
keep my fork in sync with the project (RTFM, right ? :smile: ). Once I'm
finished configuring, I will do a PR.

**Comment by icebob** [comment]
Maybe: https://help.github.com/articles/syncing-a-fork/ :)

**Comment by lionel-bijaoui** [comment]
#27

**Comment by lionel-bijaoui** [comment]
I would like to do the alternative style if possible.

**Comment by icebob** [comment]
Ok, it's good!

**Comment by icebob** [comment]
@lionel-bijaoui would you like to create a custom css styles to demonstrate this new feature on fiddle or codepen or webpackbin? Not problem if not.

**Comment by lionel-bijaoui** [comment]
Yeah, I was waiting for the official fiddle to start hacking :)

**Comment by icebob** [comment]
Great! You can use it as a base. It is updated and removed bootstrap dependency: https://jsfiddle.net/icebob/0mg1v81e/

**Comment by lionel-bijaoui** [comment]
Done : https://jsfiddle.net/0mg1v81e/31/
I used this [example (Form Style 4)](https://www.sanwebe.com/2014/08/css-html-forms-designs) to get started. I hope you like the result.

**Comment by icebob** [comment]
Great! Good job!
