### ISSUE TITLE
Resources links broken in documentation

### ISSUE THREAD

**Issue by ReynerHL** [icebob/vue-form-generator#200]
In the "**Styling the form**" section (https://icebob.gitbooks.io/vueformgenerator/content/styling.html) there is a link to an example hosted in jsfiddle (https://jsfiddle.net/0mg1v81e/31/) but the resources "**vue-form-generator.js**" (https://rawgit.com/icebob/vue-form-generator/master/dist/vue-form-generator.js) is broken and that is why the example is not running well. Great project, by the way.

**Comment by icebob** [comment]
Thanks. Fixed in docs.

>New fiddle: https://jsfiddle.net/0mg1v81e/402/
