### ISSUE TITLE
How to set default (current date) and display date format placeholder in Firefox?

### ISSUE THREAD

**Issue by sjordan1975** [icebob/vue-form-generator#204]
I created a fiddle https://jsfiddle.net/sjordan/r81k8240/

In Chrome the placeholder "mm/dd/yyyy" is present.

In Firefox it is not. Also, in Firefox, the calendar input does not pop up.

Also, I tried to use the "set" property (but no success) to set value to current date. How do I use "set"?

**Comment by lionel-bijaoui** [comment]
You will find more information about this by reading this issue #231
To put it simply, Firefox is [not yet compatible](https://caniuse.com/#search=date) with the native `<input type="date">`. It has nothing to do with us. As you can see, it is also not compatible with IE and Safari.
Read #231 for more info.
