### ISSUE TITLE
anyway to use select with ajax?

### ISSUE THREAD

**Issue by jackbbhua** [icebob/vue-form-generator#207]
like i have a address form.when i select country USA.so i need reload all state of USA.then i choose CA
if i choose Canada it need reload  all state of canada.
i had try like this:

            {
              type: "input",
              inputType: "text",
              label: "state",
              model: "state",
              placeholder: ""
            },
            {
              type: "input",
              inputType: "text",
              label: "postalCode",
              model: "postalCode",
              placeholder: ""
            },
            {
              type: "select",
              label: "country",
              model: "country",
              placeholder: "",
              values: function() {
                var cc = ''
                this.$http.get('http://api.com/country').then((response) => {
                  if (response.status == 200) {
                    var cc = response.data
                    return cc
                  }
                })
              }

the select can not render well.it is only works like this:

```
{
    type: "select",
    label: "Language",
    model: "lang",
    required: true,
    values: function() {
      return [
        { id: "en-GB", name: "English (GB)" },
        { id: "en-US", name: "English (US)" },
        { id: "de", name: "German" },
        { id: "it", name: "Italic" },
        { id: "fr", name: "French" }
      ]
    }),
    default: "en-US",
    validator: validators.required
}

```

please help .thank you

**Comment by lionel-bijaoui** [comment]
I created a custom field for this kind of feature. As far as I know this is the only way to something like that.

**Comment by ihsanberahim** [comment]
It is doable. Here the simulation.

```
 export default {
  data() {
   return {
    list: [],
      schema: {
       fields: [
        {
         type: "select",
         label: "Field 1",
         model: "field_one",
         required: true,
         values: function() {
          return this.$parent.$parent.list;
         },
        }
       ]
      },
   }
 },
  mounted() {
   var vm = this;
   setTimeout(function() {
    vm.countries.push({ id: "en-GB", name: "English (GB)" });
   }, 3000);
  }
}
```
