### ISSUE TITLE
How to hide the noneSelectedText in a select dropdown?

### ISSUE THREAD

**Issue by obiwarn** [icebob/vue-form-generator#210]
I have selects with default values & `required = true`.
How can I remove the "Please select" text option.

**Comment by keybrdist** [comment]
Just ran into the same issue. 

CSS work-around (for now):
`option[value=""] { display:none; }`

If you need options with blank value then use javascript with DOM selector (must go in mounted)

jQuery
`mounted () {  $('option:contains("<Nothing selected>")').hide() }
`

**Comment by lionel-bijaoui** [comment]
My PR #237 should fix this issue. I'm waiting for @icebob validation.
Just add `hideNoneSelectedText` in `selectOptions` and this `<option>` won't be added.
No need for CSS hack anymore \o/
