### ISSUE TITLE
Unknown custom element: <multiselect> when using vueMultiSelect latest version

### ISSUE THREAD

**Issue by EmmaAkin** [icebob/vue-form-generator#212]
package.json file
` "dependencies": {
    "chartist": "^0.10.1",
    "chartist-plugin-pointlabels": "0.0.4",
    "font-awesome": "^4.7.0",
    "highlightjs": "^9.8.0",
    "jquery": "^3.1.1",
    "select2": "^4.0.3",
    "vue": "^2.1.0",
    "vue-chartist": "^2.0.2",
    "vue-datatable": "^1.0.4",
    "vue-multiselect": "^2.0.0-beta.15",
    "vue-router": "^2.1.1",
    "vue-strap": "^1.1.34",
    "vuex": "^2.1.1"
  }`
main.js file
`import VueFormGenerator from "vue-form-generator/dist/vfg-core.js"
import Multiselect from 'vue-multiselect'

Vue.use(VueFormGenerator)
Vue.use(Multiselect)

 Vue.component(Multiselect)`

Component
`<script>
import VueFormGenerator from "vue-form-generator"
import Multiselect from 'vue-multiselect'

window.VueMultiselect = Multiselect

  export default {
    name: 'FormPage',
    data() {
            return {
                          model:{
                          title:"",
                          propertyType:'',
                          subcategory:"",
                          streetaddress:"",
                          region:'',
                          city:''

                          },
                          selected: null,
                          options: ['list', 'of', 'options'],
                          formOptions: {
                          validationErrorClass: "has-error",
                          validationSuccessClass: "has-success",
                          validateAfterChanged: true
                          },
                          firstTabSchema:{
                                 fields:[{
                                              type: "input",
                                              inputType: "text",
                                              label: "Title",
                                              model: "title",
                                              required:true,
                                              validator:VueFormGenerator.validators.string,
                                              styleClasses:'col-xs-6'
                                           },
                                           {
                                              type: "vueMultiSelect",
                                              multiSelect: false,
                                              placeholder: "Select your property type",
                                              label: "Property Type",
                                              model: "propertyType",
                                              required:true,
                                              selectOptions:{
                                                  key:"name",
                                                  label:"name",
                                                  searchable: true,
                                                  customLabel: function({name}){
                                                    return `${name}`
                                                  }
                                              },
                                              values:[
                                                  {
                                                    "name": "Vue.js"
                                                  },
                                                  {
                                                    "name": "Rails"
                                                  },
                                                  {
                                                    "name": "Sinatra"
                                                  }
                                              ],
                                              styleClasses:'col-xs-6'
                                           },
                                          {
                                            type: "input",
                                            inputType: "text",
                                            label: "Subcategory",
                                            model: "subcategory",
                                            required:true,
                                            validator:VueFormGenerator.validators.string,
                                            styleClasses:'col-xs-6'
                                         },
                                          {
                                            type: "input",
                                            inputType: "text",
                                            label: "Street Address",
                                            model: "streetAddress",
                                            required:true,
                                            validator:VueFormGenerator.validators.string,
                                            styleClasses:'col-xs-6'
                                         },

                                          {
                                            type: "input",
                                            inputType: "text",
                                            label: "Region",
                                            model: "region",
                                            required:true,
                                            validator:VueFormGenerator.validators.string,
                                            styleClasses:'col-xs-3'
                                         },
                                          {
                                            type: "input",
                                            inputType: "text",
                                            label: "City",
                                            model: "city",
                                            required:true,
                                            validator:VueFormGenerator.validators.string,
                                            styleClasses:'col-xs-3'
                                         }
                                         ]
                          },
                          secondTabSchema:{
                                     fields:[
                                               {
                                                  type: "input",
                                                  inputType: "text",
                                                  label: "Bath",
                                                  model: "bath",
                                                  required:true,
                                                  validator:VueFormGenerator.validators.string,
                                                  styleClasses:'col-xs-4'
                                               },
                                              {
                                                type: "input",
                                                inputType: "text",
                                                label: "Bed",
                                                model: "bed",
                                                required:true,
                                                validator:VueFormGenerator.validators.string,
                                                styleClasses:'col-xs-4'
                                              },
                                              {
                                                type: "input",
                                                inputType: "text",
                                                label: "Room",
                                                model: "room",
                                                required:true,
                                                validator:VueFormGenerator.validators.string,
                                                styleClasses:'col-xs-4'
                                              },
                                              {
                                                type: "select",
                                                label: "Living area (square meters)",
                                                model: "livingarea",
                                                required:false,
                                                validator:VueFormGenerator.validators.string,
                                                values:['United Kingdom','Romania','Germany'],
                                                styleClasses:'col-xs-6'
                                              },
                                              ]
                          },
                           thirdTabSchema:{
                                     fields:[
                                               {
                                                  type: "input",
                                                  inputType: "text",
                                                  label: "Bath",
                                                  model: "bath",
                                                  required:true,
                                                  validator:VueFormGenerator.validators.string,
                                                  styleClasses:'col-xs-4'
                                               },
                                              {
                                                type: "input",
                                                inputType: "text",
                                                label: "Bed",
                                                model: "bed",
                                                required:true,
                                                validator:VueFormGenerator.validators.string,
                                                styleClasses:'col-xs-4'
                                              },
                                              {
                                                type: "input",
                                                inputType: "text",
                                                label: "Room",
                                                model: "room",
                                                required:true,
                                                validator:VueFormGenerator.validators.string,
                                                styleClasses:'col-xs-4'
                                              },
                                              {
                                                type: "select",
                                                label: "Living area (square meters)",
                                                model: "livingarea",
                                                required:false,
                                                validator:VueFormGenerator.validators.string,
                                                values:['United Kingdom','Romania','Germany'],
                                                styleClasses:'col-xs-6'
                                              },
                                              ]
                          },
                           fourthTabSchema:{
                                     fields:[
                                               {
                                                  type: "input",
                                                  inputType: "text",
                                                  label: "Bath",
                                                  model: "bath",
                                                  required:true,
                                                  validator:VueFormGenerator.validators.string,
                                                  styleClasses:'col-xs-4'
                                               },
                                              {
                                                type: "input",
                                                inputType: "text",
                                                label: "Bed",
                                                model: "bed",
                                                required:true,
                                                validator:VueFormGenerator.validators.string,
                                                styleClasses:'col-xs-4'
                                              },
                                              {
                                                type: "input",
                                                inputType: "text",
                                                label: "Room",
                                                model: "room",
                                                required:true,
                                                validator:VueFormGenerator.validators.string,
                                                styleClasses:'col-xs-4'
                                              },
                                              {
                                                type: "select",
                                                label: "Living area (square meters)",
                                                model: "livingarea",
                                                required:false,
                                                validator:VueFormGenerator.validators.string,
                                                values:['United Kingdom','Romania','Germany'],
                                                styleClasses:'col-xs-6'
                                              },
                                              ]
                          }
                    }
          },
 methods: {
  onComplete: function(){
      alert('Yay. Done!');
   },
   validateFirstTab: function(){
     return this.$refs.firstTabForm.validate();
   },
   validateSecondTab: function(){
     return this.$refs.secondTabForm.validate();
   },
   validateThirdTab: function(){
     return this.$refs.thirdTabForm.validate();
   },
   validateFourthTab: function(){
     return this.$refs.fourthTabForm.validate();
   },
    prettyJSON: function(json) {
            if (json) {
                json = JSON.stringify(json, undefined, 4);
                json = json.replace(/&/g, '&').replace(/</g, '<').replace(/>/g, '>');
                return json.replace(/("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g, function(match) {
                    var cls = 'number';
                    if (/^"/.test(match)) {
                        if (/:$/.test(match)) {
                            cls = 'key';
                        } else {
                            cls = 'string';
                        }
                    } else if (/true|false/.test(match)) {
                        cls = 'boolean';
                    } else if (/null/.test(match)) {
                        cls = 'null';
                    }
                    return '<span class="' + cls + '">' + match + '</span>';
                });
            }
        }
   },
   components:{
        Multiselect
   }

  }
</script>`

When I added to the package.json this
  `"vue-multiselect": "next", as per [here](https://github.com/icebob/vue-form-generator/issues/100)`
It worked
but there is this new error 
vue.common.js:436 [Vue warn]: Unknown custom element: <field-vueMultiSelect> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by icebob** [comment]
Please format better the content of your message.

**Comment by lionel-bijaoui** [comment]
Here is the guide to use [Github Markdown](https://guides.github.com/features/mastering-markdown/). Also, provide a jsfiddle so we can test the problem.
