### ISSUE TITLE
Image preview: How to display and bind remove button?

### ISSUE THREAD

**Issue by keybrdist** [icebob/vue-form-generator#213]
I see the empty div with class="remove" but it doesn't appear to be functional. It doesn't display when an image is chosen (or prefilled).  The image appears, but the 'remove' button does not.  Not sure how to make use of it.  Can someone explain?

**Comment by keybrdist** [comment]
I've used CSS to display an X icon inside the div and that works ok.. just not sure this is how it's meant to be used.

**Comment by icebob** [comment]
The preview icon is in the style of component. You need to import the vfg.css if you want to see it.
