### ISSUE TITLE
Stable v2 release

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#220]
I think we are close to the stable v2 of vfg.
I found [2 issues](https://github.com/icebob/vue-form-generator/issues?q=is%3Aissue+is%3Aopen+label%3A%22before+v2+stable%22) what we need to fix before it.

What do you think @lionel-bijaoui @dflock ?

**Comment by dflock** [comment]
Looks about right to me; I added them to the milestone. I will try to get to these tomorrow, but no promises ;)

**Comment by icebob** [comment]
I fixed the #138. And will try the #215 too, if I have time.

**Comment by lionel-bijaoui** [comment]
We still need the dev environment to be updated (along with the tests). I have no idea how much work on documentation is necessary.
Other than that, all I have to say is : ["Hell, it's about time"](https://www.youtube.com/watch?v=_J6-3l3hCm0)

**Comment by icebob** [comment]
#215: no bug

**Comment by icebob** [comment]
I'm starting to release v2 stable

**Comment by icebob** [comment]
[Released stable v2!](https://github.com/icebob/vue-form-generator/releases/tag/v2.0.0)
Please try somebody who can.
