### ISSUE TITLE
option to put multiple fields on one line

### ISSUE THREAD

**Issue by jamesdixon** [icebob/vue-form-generator#224]
Hi again,

Is there any sort of option to allow multiple fields to exist on a single line? For example, I have an address section where it would be great to allow the city, state and zipcode columns to all live on a single line.

Thanks! And more importantly, thanks for your hard work on this project!

**Comment by icebob** [comment]
Hi @jamesdixon,
yes there is. You need create custom css class and set it to fields to `styleClasses`. 
Example: [schema field](https://github.com/icebob/vue-form-generator/blob/master/dev/full/schema.js#L45) and  [CSS](https://github.com/icebob/vue-form-generator/blob/master/dev/full/app.vue#L290)

**Comment by jamesdixon** [comment]
Thank you!
