### ISSUE TITLE
Custom field without label, inputName or model results in error

### ISSUE THREAD

**Issue by will-fgmnt** [icebob/vue-form-generator#225]
Failing to not specify any of these on a custom fields results in the following error:

```
vue.esm.js?65d7:1452 TypeError: Cannot read property 'toString' of undefined
    at e.exports.slugifyFormID (eval at <anonymous> (app.js:806), <anonymous>:7:12306)
    at VueComponent.getFieldID (eval at <anonymous> (app.js:806), <anonymous>:7:5340)
    ...
```

The documentation could be made a little clearer to specify at lease one of these values is required. Our particular use-case was we have a custom submit button which doesn't have a label or model.

**Comment by dflock** [comment]
Haven't got time to properly test this now, but probably changing `src/utils/schema.js:65` from this:

```js
return prefix + (schema.inputName || schema.label || schema.model)
```

to this:

```js
return prefix + (schema.inputName || schema.label || schema.model || '')
```
would fix this.

**Comment by icebob** [comment]
Is it solved the problem? If yes, @dflock could you fix it in the repo?

**Comment by dastiw1** [comment]
@icebob It works for me. Thank you. I don't know how to send pull request)
