### ISSUE TITLE
default style for select

### ISSUE THREAD

**Issue by jamesdixon** [icebob/vue-form-generator#228]
Hi,

All of the components seem to have a matching style, except for the `select` element. Is this intentional?

[Example fiddle](https://jsfiddle.net/qhhnzd5e/)

Thanks!

**Comment by lionel-bijaoui** [comment]
It's weird, on my machine, I see the select field with a matching style. What is your browser ?

**Comment by jamesdixon** [comment]
Latest version of Chrome on Mac.

Just to be clear, here's what I'm seeing:

![image](https://user-images.githubusercontent.com/110114/27040248-b271c540-4f4d-11e7-9c55-f896dfba3410.png)

When I say style, I'm specifically talking about the select height compared to other elements.

**Comment by lionel-bijaoui** [comment]
I don't have a Mac so I can't really help. I've tested on Chrome 59 and Firefox 53 on Windows and no problem. I don't know what is doing that.

**Comment by dflock** [comment]
Select boxes are notoriously inconsistent and hard to style, especially on
MacOS:

https://stackoverflow.com/q/2547354/259698

**Comment by jamesdixon** [comment]
@dflock it certainly appears that way! Ultimate, I added a `height` attribute that matches the default styling. Seems to work across modern browsers
