### ISSUE TITLE
Can't post DATA

### ISSUE THREAD

**Issue by Katyucha** [icebob/vue-form-generator#230]
Hi,
I'm using for the first time this generator and I don't understand how to post data 

I just wrote this jsfiddle : https://jsfiddle.net/0mg1v81e/453/ to use your example and post data to a httpbin/data (to look how the form is post)  

I just add a submit button, the form look good but when I validate the form, no data are posted.. .

Can anyone can help or explain.. Thanks

**Comment by icebob** [comment]
If you want to POST data, you need define "inputName" props in fields. Please check [this example](https://github.com/icebob/vue-form-generator/blob/master/examples/post-form/main.js#L59)

Fixed fiddle: https://jsfiddle.net/0mg1v81e/457/

**Comment by Katyucha** [comment]
I'm SO idiot !! I don't see inputName are absent :/ Sorry :/
