### ISSUE TITLE
How to use pikaday for cross-browser date selection?

### ISSUE THREAD

**Issue by sjordan1975** [icebob/vue-form-generator#238]
I am trying to use pikaday as an alternative to bugs raised by #231.

However, I cannot seem to get dates to work.

I have created a [fiddle](https://jsfiddle.net/sjordan/6tkhy8m9/).

Issues I'm facing:

1. The form has the same bug as #231. Entering values with the keyboard gives incorrect results.
2. Selecting a value from the pop-up calendar does not seem to set the model value. Note, the value of dob in the model does not change.

Please update my example to demonstrate the use of pikaday.

**Comment by icebob** [comment]
The field is working, but there was a circular JSON stringify error when tried to `prettyJSON` the schema.

**Comment by sjordan1975** [comment]
How about the first point; I seem unable to successfully enter a pick using the keyboard

**Comment by cesarmarinhorj** [comment]
pikadayOptions: {
onSelect: function(date){
		vm.model.myDate = date;
		console.log(date);
	}
}

**Comment by sjordan1975** [comment]
@cesarmarinhorj Hi Cesar. Can you provide more explanation? What am I supposed to do with this information? Where does it go in the code? What is this reference to pikadayOptions? How is it passed/used? Maybe a fiddle would be useful.

Thank you

**Comment by raphaelarias** [comment]
@cesarmarinhorj Thanks for the snippet. My pikaday input was returning false (!?), with your snippet it works, but it is still a hack. I have to understand what is happening and fix it properly. So for future references and if someone is having the same problem: my input returns false, and as soon as you select for the first time it returns 1970-01-01, and even though after the second selection it works, the model has the "false" boolean value.

When/if I find the solution I post here.
