### ISSUE TITLE
Help to update VueMultiselect partial functionnality

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#239]
The goal here is to update to the new API of VueMultiselect v2 (kinda relate to #193).
So far, I did the easiest part, cleaning old and unused props and adding the missing one. I also reordered the props to fit [the documentation](http://monterail.github.io/vue-multiselect/#sub-props).

My biggest challenge so far is the new way to do custom rendering of the list.
Before, it was using Vue partials. But since Vue added scoped slot, they decided to use that instead.
The problem is that I don't see how we can implement an interface to send template elements into this slot.
I have little experience with scoped slot, but I'm not comfortable with them.
I always have a hard time wrapping my head around the concept, and this is another level of complexity.

So if anyone could help me find a nice solution, that would be very helpful.

PR here #240

**Comment by icebob** [comment]
Thanks the PR. 
Currently I don't know also how we can add scoped slots to multiselect field. 

Workaround: if somebodies want to use custom multiselect listing, they need to create custom fields with slots :)

**Comment by lionel-bijaoui** [comment]
@icebob If we drop this functionality (at least for now), I can finish this faster. You validate ?

**Comment by icebob** [comment]
I think it is a bigger development (scoped slots thing), so I suggest to make it later, after the stable v2.

**Comment by icebob** [comment]
@lionel-bijaoui full dev example is not working after #240.
![image](https://user-images.githubusercontent.com/306521/27729128-d69605b8-5d84-11e7-8c20-9ce8cd49c1a8.png)

**Comment by lionel-bijaoui** [comment]
#245 will fix it

**Comment by icebob** [comment]
Thx. It works.
