### ISSUE TITLE
update docs for v0.4.0

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#25]
- [x] vue-multiselect field #20
- [x] fieldSubmit #26 
- [x] customizable styles #29 
- [x] fieldCleave #31
- [x] fieldPikaday #31
- [x] fieldNoUiSlider #31
- [x] fieldGoogleAddress #33 
- [x] visible & disabled, values schema functions description
- [x] ES5 examples (change `visible(model) {...}` to visible: `function(model) {...}` )

**Comment by lionel-bijaoui** [comment]
Need help with the doc ?

**Comment by icebob** [comment]
Maybe :smiley:

**Comment by lionel-bijaoui** [comment]
Go on, tell me: how can I help?

**Comment by icebob** [comment]
The docs on gitbook.com. I don't know it enough good, I don't know the contribution is available.

**Comment by lionel-bijaoui** [comment]
I just created an account on gitbook, please authorize me so I can try.

**Comment by icebob** [comment]
OK, I added.

**Comment by icebob** [comment]
Please check, can you modify the docs?

**Comment by lionel-bijaoui** [comment]
YES ! :tada:

**Comment by icebob** [comment]
Great!

**Comment by lionel-bijaoui** [comment]
Maybe we should specify "vanilla vs jQuery" in the `installation.md`? I fear the dependency list could be misunderstood and seem daunting. Maybe dependency should be specified only for each field ?

**Comment by icebob** [comment]
Yes we need specify dependencies for every each field

**Comment by lionel-bijaoui** [comment]
I'm going to create a branch on gitbook for the v0.4.0 and start modifying the doc

**Comment by icebob** [comment]
Great! Thanks!

**Comment by lionel-bijaoui** [comment]
I don't understand what `multiple` do, can you explain please ?
It is listed in `component.md` and `fields/field_properties.md`, is it two different options, or a mistake ?

**Comment by icebob** [comment]
You can test in in dev mode. Use CTRL key and select multiple rows in table. In this case you can edit fields for multiple models. And component shows fields where `multiple: true`.

But currently it is not complete, because validator can't handle it correctly yet.

**Comment by lionel-bijaoui** [comment]
So the main `multi` activate the option, and field level `multi` activate each field to be part of it ?

**Comment by icebob** [comment]
Has `multi` and `multiple`. Both exists.
Field has property `multi`.
Component has `multiple`˛which activate this "multi mode".
See in dev example:
```js
vue-form-generator(:schema='schema', :model='model', :multiple="selected.length > 1")
```
So if we select 2 or more rows we set `multiple` to true

**Comment by lionel-bijaoui** [comment]
Ok I get it :cool:

**Comment by lionel-bijaoui** [comment]
@icebob I just finished vueMultiselect documentation (on branch v0.4.0), I need your feedback.

**Comment by icebob** [comment]
Great!

I checked it.

- did you tried the usage examples? Because I think it is not working properly:
```js
  values: [
    {
      "name": "Vue.js",
      "language": "JavaScript"
    },
```
VueFormGenerator is only handle `{id: 1, name: ''}` objects as item of values.
Because when you select the item, the component write the value of `id` field only to the model property. 

- There is no link to the page. Missing from `Fields` page: https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/fields/README.md

Otherwise, good job! Thank you :+1:

**Comment by lionel-bijaoui** [comment]
- I haven't tested it, but with `key` and `label` allow for a total control on your object.
- Yes, I still have work to do. Have you checked [this page](https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/installation.md)

**Comment by lionel-bijaoui** [comment]
@icebob noUiSlider is almost done (need more examples)
I have checked and tested all examples for vueMultiselect and noUiSlider and fixed a few things.

**Comment by icebob** [comment]
Great!

**Comment by lionel-bijaoui** [comment]
@icebob noUiSlider and cleave are finished. Example tested and everything :tada:

**Comment by icebob** [comment]
For https://github.com/icebob/vue-form-generator/issues/40#issuecomment-242761754 :

**fieldSubmit:** only a simple input type=submit. There is a `validateBeforeSubmit` property in schema. If it is true, running validation after button click. If validation success, call the onSubmit callback from the schema

**Comment by icebob** [comment]
**customizable styles**: we can show with example that user can use custom styles for this component. You created a jsfiddle with a new style. You can link it to docs as an example.

**Comment by icebob** [comment]
**visible & disabled, values schema functions description:**

`visible` and `disabled` property in the schema can be a function too. [Example](https://github.com/icebob/vue-form-generator/blob/master/dev/schema.js#L163)
The function got the model as parameter.

`values` property in `select*` fields can be a function. In this case you can generate dynamically the items. [Example](https://jsfiddle.net/6xh0e3nx/1/). This function gets the `model` and `schema` as parameters.
You can use this example in docs too.
```js
{
    type: "select",
    label: "Item",
    model: "item",
    values: function(model, schema) {
		switch(model.category) {
			case "Fruit": return ["Apple", "Peach", "Orange"];
			case "Vehicle": return ["Car", "Bicycle", "Ship"];
			case "Animals": return ["Lion", "Dog", "Cat"];
		}
		
		return [];
	}
}
```

**Comment by lionel-bijaoui** [comment]
@icebob pikaday field done !

**Comment by icebob** [comment]
1 observation: spectrum is a jQuery based field. Currently it is under "vanilla"

**Comment by lionel-bijaoui** [comment]
Sorry, I missed that. It is not very explicit.

**Comment by icebob** [comment]
Thanks. Could you make all docs tasks? Because after it, I will release v0.4.0

**Comment by lionel-bijaoui** [comment]
I'm will do it when I'm at work

**Comment by lionel-bijaoui** [comment]
Please check :
- [fieldSubmit](https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/fields/submit.md)
- [fieldGoogleAddress](https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/fields/googleaddress.md)

**Comment by icebob** [comment]
I added `caption` and `onSubmit` to fieldSubmit. Please check the typo.

**Comment by lionel-bijaoui** [comment]
What is really `caption` ? I don't get it. Is it the text on the button submit ?

**Comment by icebob** [comment]
yes

**Comment by icebob** [comment]
I added `onPlaceChanged` to googleAddress field.

**Comment by lionel-bijaoui** [comment]
Why not call it `text` then ? Or `textButton` ?

**Comment by icebob** [comment]
`text` is too common. But change to `buttonText`

**Comment by lionel-bijaoui** [comment]
I have reorganize the build in field alphabetically

**Comment by icebob** [comment]
Please do it on optional fields too.

**Comment by lionel-bijaoui** [comment]
Ok

**Comment by lionel-bijaoui** [comment]
I think I'm done. Sorry for the delay, I was very busy at work yesterday.

**Comment by lionel-bijaoui** [comment]
The `schema` on [this page](https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/usage.md) is `{...}`. Should we not write what the `schema`look like in details ?

**Comment by icebob** [comment]
Ok, do it

**Comment by lionel-bijaoui** [comment]
@icebob I have made some reorganization to the [structure](https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/SUMMARY.md) and properties [here](https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/component.md)

**Comment by icebob** [comment]
I moved your screenshot to the `assets`, ok?
https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/assets/Capture%20d%E2%80%99%C3%A9cran%202016-08-29%20%C3%A0%2017.39.15.png

**Comment by lionel-bijaoui** [comment]
Oh sorry about that crappy screenshot (badly cropped), I was just a test to see if I could upload a photo to gitbook. You can delete it :)

**Comment by icebob** [comment]
Ok :)

**Comment by icebob** [comment]
I add a new tasks to this issue, but I'm doing

**Comment by lionel-bijaoui** [comment]
Ok i'm done with [schema example](https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/usage.md)

**Comment by icebob** [comment]
Great! Thanks

**Comment by icebob** [comment]
So all tasks done?

**Comment by lionel-bijaoui** [comment]
I guess so, I looking at the documentation, trying to find problems

**Comment by icebob** [comment]
OK

**Comment by lionel-bijaoui** [comment]
Maybe there a thing, but it is more an improvement than a real problem.

For field like [pikaday](https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/fields/pikaday.md) or [noUiSlider](https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/v0.4.0/fields/nouislider.md), I have added default values. Most fields don't have that information.
I guess it can be improved later and is non blocking for the merge.

What do you think ?

**Comment by icebob** [comment]
Yes, it is a good idea. But for this open a new issue and we do it later.

**Comment by lionel-bijaoui** [comment]
Roger that!
I think we are go :)

**Comment by icebob** [comment]
Thank you for your contribution!

**Comment by lionel-bijaoui** [comment]
You are welcome, thank you for your work on the plugin :+1:

**Comment by icebob** [comment]
I'm making the new release. Could you merge the docs branch to the master?

**Comment by lionel-bijaoui** [comment]
Done

**Comment by icebob** [comment]
New version released: https://github.com/icebob/vue-form-generator/releases/tag/v0.4.0

**Comment by lionel-bijaoui** [comment]
That crazy list of changes :D
