### ISSUE TITLE
Checklist bootstrap styling

### ISSUE THREAD

**Issue by flakobatako** [icebob/vue-form-generator#251]
Contrary to the traditional select, using a checklist, the style is broken when using bootstrap (the bg color of the list is transparent, doesn't show the arrow).

Based on the demo: https://jsfiddle.net/zoeabsL4/

Is there any work around?

Thanks in advance

**Comment by icebob** [comment]
Workaround if you add [vfg.css](https://unpkg.com/vue-form-generator/dist/vfg.css)
https://jsfiddle.net/icebob/zoeabsL4/1/
