### ISSUE TITLE
"default" option for select broken

### ISSUE THREAD

**Issue by CmdrSharp** [icebob/vue-form-generator#252]
The default selector for dropdown selects doesn't appear to actually default anything. This is a Fiddle showcasing a replica of the example usage from the documentation:

https://jsfiddle.net/4pmcyju3/1/

**Comment by CmdrSharp** [comment]
Appears to be the case with other elements such as checkboxes too.

https://jsfiddle.net/4pmcyju3/2/

**Comment by icebob** [comment]
The `˛default` property is not used in vfg fields. It is used when you create a new model by schema.

https://icebob.gitbooks.io/vueformgenerator/content/model.html

**Comment by zoutepopcorn** [comment]
I have the same issue.

Only solving it with using model

https://jsfiddle.net/zoutepopcorn/0Lj3w9au/1/

**Comment by Aterr** [comment]
+1 to @zoutepopcorn
