### ISSUE TITLE
Question:  styleClasses usage

### ISSUE THREAD

**Issue by jionlab205** [icebob/vue-form-generator#254]
VFG is fantastic component that I looking for! thanks in advance.  
Hope to use it my scratch project , but I am novice to VUE,  need some help. 

I would like to  change style for my style.  I use single .Vue file that contain template, script, style. 
To show the field "Name" label as Red and Big,    I added the styleClasses "name-field" ,  as below.

schema: {
   fields: [{  
          type: 'input',
          inputType: 'text',
          label: 'Name',
          model: 'name',
          styleClasses: 'name-field',
          readonly: false,
 ...

And Add style as below --> 

<style lang='scss' scoped>

fieldset.vue-form-generator {
		.form-group.name-field {
	            font-size : 100px;
                    backgound-color: red;
		}
	 
}
</style>

But the "name" field font-size and color not changed. Can you fugure out What I missing?

thanks

**Comment by icebob** [comment]
The problem is that it won't work with scoped styles.
Create a non-scoped style block too.
```html
<style lang='scss'> 
    fieldset.vue-form-generator { 
           .form-group.name-field { 
                font-size : 100px; backgound-color: red; 
             }
      } 
</style>
```
