### ISSUE TITLE
Form is not reactive

### ISSUE THREAD

**Issue by Eduardoveras** [icebob/vue-form-generator#256]
When I update the values after rendering the VFG, the component is not updated. im setting the disabled field dinamically and its not updating,  

(will update with fiddle)

**Comment by Eduardoveras** [comment]
https://jsfiddle.net/eduardoveras94/dhv2txz9/2/ 

Seems like its not possible to give the schema a variable as value, it always take the input as false

note: check isDisabled value on lines 25 and 27

**Comment by ChadTaljaardt** [comment]
Is there any update with this? I need this too.

**Comment by Eduardoveras** [comment]
@ChadTaljaardt No updates, the only way is bad hacks and modifying the schema in real time

**Comment by cristijora** [comment]
The only way I know how to do it is to search the field inside the schema
https://jsfiddle.net/dhv2txz9/14/

`var nameField  = this.schema.fields.find(field => field.model === 'name')` and then adjust it the way you need. You can make a helper function for example and give it the model name,

`getField(this.schema, 'name')`

**Comment by Eduardoveras** [comment]
Thank you! this seems to fix the problem
