### ISSUE TITLE
Conflict .wrapper class with Paper Dashboard Template

### ISSUE THREAD

**Issue by phuongtailtranminh** [icebob/vue-form-generator#261]
Hi,
I'm currently using Paper Dashboard Template for my project.
But it seems likes the `.wrapper` class is conflicted, it makes the input is very far away from each other.

![image](https://user-images.githubusercontent.com/12473996/28349435-0fd90fea-6c6d-11e7-92e3-79539e3a237b.png)

The problem was disappeared when I removed the `.wrapper` class inside `.field-wrap`

![image](https://user-images.githubusercontent.com/12473996/28349512-730be98e-6c6d-11e7-97bc-9b87c00af850.png)

**Comment by phuongtailtranminh** [comment]
My current solution is using jquery is remove the class after mounted() 

It look likes this:

```
  mounted () {
    $('.field-wrap>div').removeClass('wrapper')
  },
```

I just want to know if there is any elegant solution

**Comment by icebob** [comment]
Sorry, but currently there is no better solution. The style classes is hard coded.

**Comment by phuongtailtranminh** [comment]
Thank you 👍
