### ISSUE TITLE
using vue-form-generator with other css frameworks

### ISSUE THREAD

**Issue by reusr1** [icebob/vue-form-generator#262]
Currently vue-form-generator and some of the field types are bound to bootstrap.css. We're using another css framework in our application. It may be a good idea to set a theme in the options of vue-form-generator or a callback that allows for switching components between different frameworks

When rendering a form field this would allow for a resolution of what component to use to render the field (eg first look if field-{theme}-{name} is available before using field-{name})

**Comment by reusr1** [comment]
thanks for the response. In our case we use http://materializecss.com/forms.html - in this case we for example had to replace the datepicker. I don't think it's the job of vfg to provide for all different types of css frameworks. What I think may be a good idea to be a bit more css framework agnostic in the basic components and allow 3rd parties to develop for different css frameworks. 
While the approach of adding classes works it does not seem to be the best approach if you have a large set of schemas as you would have to add the classes to every schema resulting in a lot of duplicate work. 
If a theme is introduced the vfg options could also contain the basic custom classes per field to be added as a more global approach.

**Comment by lionel-bijaoui** [comment]
I'm able to do [that](https://jsfiddle.net/0mg1v81e/558/), which isn't too bad.

As for the date picker, there is no real solution.
Have you tried Pikaday or DateTimePicker ?

It is also fairly easy to [create your own fields](https://icebob.gitbooks.io/vueformgenerator/fields/custom_fields.html). You can use the core version, and add your own fields, with your own framework in mind. We encourage you to share your work with the community of course.

We will never be able to satisfy everyone and continue to add new feature at the same time.
Good luck !

**Comment by reusr1** [comment]
thank you for the example. We intend to share our custom components in the future. Will keep you posted

**Comment by gentunian** [comment]
Hi! I'm trying to use some tool like this one but it seems to be too opinionated. I'm trying to find out how I should use it with another ui framework (i.e. bulma). The only reference I found in the docs is `styleClasses` property, can you give a clue where should I look for?

**Comment by gentunian** [comment]
Found the answer [here](https://github.com/vue-generators/vue-form-generator/issues/403), seems that online manual is outdated:
