### ISSUE TITLE
Advice please: Click button to add another text input (like adding a row of table) and binding

### ISSUE THREAD

**Issue by imylomylo** [icebob/vue-form-generator#267]
Hi Icebob,

Cool component.

Just wondering where I'd go from this example:
https://jsfiddle.net/imylomylo/xqu5mraq/2/

I'm trying to add rows to the form, like adding a row to a table - doesn't have to be elegant.
Any suggestions on how to go about it?

Cheers

**Comment by icebob** [comment]
Currently, this is the best solution to modify the schema dynamically.
