### ISSUE TITLE
Custom Validators

### ISSUE THREAD

**Issue by wahiche** [icebob/vue-form-generator#269]
I am trying to create a custom validator to test if passwords match when a user is signing up.

`confirmPasswordValidator(value, field, model) {
    let pass = model.password;
    let confPass = value;
    if (pass != confPass) {
        return ["Passwords don't match."];
    } else {
        return [];
    }
};` 

When I submit my form I have a submit button created like this:

`{
                                type: "submit",
                                buttonText: "Register",
                                onSubmit: this.onValidated,
                                validateBeforeSubmit: true
                            }`

The form submits even though the password fields do not match.

`{
                                type: "input",
                                inputType: "password",
                                label: "Password",
                                model: "password",
                                min: 6,
                                required: true,
                                hint: "Minimum 6 characters",
                                validator: VueFormGenerator.validators.string
                            }`

`
                            {
                                type: "input",
                                inputType: "password",
                                label: "Confirm Password",
                                model: "confirmPassword",
                                min: 6,
                                required: true,
                                hint: "Minimum 6 characters",
                                validator: this.confirmPasswordValidator
                            }`

How do I stop the form from submitting when there are errors?

**Comment by cristijora** [comment]
See this example
https://jsfiddle.net/0mg1v81e/695/

Add `v-on:submit.prevent` modifier on your form to prevent submit and make sure your `data` is a function so `this.onValidated` will call the appropriate function

**Comment by wahiche-architech** [comment]
I will try that out later tonight.  Thanks.  I will let you know if it did not work.
