### ISSUE TITLE
ability to add another field set in an array

### ISSUE THREAD

**Issue by DelfsEngineering** [icebob/vue-form-generator#270]
What is the best way to handle scenarios where you have a few fields grouped and form an address, and want to add _another_ address. Eg. Work then home the cottage etc. 

Typically you would see a [+] plus button that would create another row of fields for the user.

**Comment by lionel-bijaoui** [comment]
Your best solution is to look into [custom fields](https://icebob.gitbooks.io/vueformgenerator/fields/custom_fields.html) and implement this yourself.
Good luck !
