### ISSUE TITLE
using vueformgenerator with veevalidate

### ISSUE THREAD

**Issue by EmmaAkin** [icebob/vue-form-generator#275]
The fieldset tag in the **vueforgenerator** does not load the element when **veevalidate** plugin is used. 
And no error is displayed in the console even when all conflicts are resolved with this fix.
`const config = {
  errorBagName: 'errors', // change if property conflicts.
  fieldsBagName: 'fields', 
  delay: 0, 
  locale: 'en', 
  dictionary: null, 
  strict: true, 
  classes: false, 
  classNames: {
    touched: 'touched', // the control has been blurred
    untouched: 'untouched', // the control hasn't been blurred
    valid: 'valid', // model is valid
    invalid: 'invalid', // model is invalid
    pristine: 'pristine', // control has not been interacted with
    dirty: 'dirty' // control has been interacted with
  },
  events: 'input|blur',
  inject: true
};`

**Comment by lionel-bijaoui** [comment]
VFG doesn't work with veevalidate unfortunately
