### ISSUE TITLE
Select option id + name without a function

### ISSUE THREAD

**Issue by Aterr** [icebob/vue-form-generator#278]
Hi there!
Having trouble with setting values in options.
I am getting all data from the server and trying to build json schema based on server response. The trouble I faced, is that I cannot set any values inside option. The value is always empty. 

The structure is:

```
var property = {

type: 'select',

label: el.Name,

id: el.Id,

selectOptions: {

noneSelectedText: 'Please select',

value: 'Please select',

hideNoneSelectedText: true

},

values: {id: '1', name: 'displayed text'},

required: true

}

```

I would be very thankful for any help.

**Comment by cristijora** [comment]
Check out this example
https://jsfiddle.net/0mg1v81e/709/

First time you run it, the select values will contain one value "Loading values..."
After 2s the values should be populated with a list of values
```
 var selectField = this.findField("skills")
 selectField.values = ["HTML5", "Javascript", "CSS3", "CoffeeScript", "AngularJS", "ReactJS", "VueJS"]
 this.model.skills = "HTML5"
```

**Comment by Aterr** [comment]
Oh, figured it out. I screwed with selectOptions.value :/
@cristijora thank you m8 for help!

But I have another probably stupid question...
How to set first option selected ?

**Comment by cristijora** [comment]
Well I assume your fields/schema will be retrieved as you said from the server.
https://jsfiddle.net/0mg1v81e/714/
You can set the model value if you know the field "model" 
`this.model[selectField.model] = selectField.values[0]`

**Comment by Aterr** [comment]
@cristijora Thank you! Gonna try it now :)
