### ISSUE TITLE
Is there any way to validate all form elements in the form ?

### ISSUE THREAD

**Issue by Aterr** [icebob/vue-form-generator#280]
Hi guys!
Just got stucked with fields validation inside generated form. I have a bunch of selects/checkboxes  etc. inside my form. And I would like to ask if there is a best practice way to validate those elements. As I looked through validation options, there are no any news about select validation, for example.
or maybe there is a way to use side validation plugin with vfg ?

Would be very pleased to hear any thoughts on this.

**Comment by icebob** [comment]
In vfg, the validator is a simple function. So you can write your custom validator functions, which check your selects.

**Comment by cristijora** [comment]
Selects either return a string or an array of strings/objects. Based on that you could use required validator for example or simply compare the value.
