### ISSUE TITLE
Looking for a good way to override behavior of VFG?

### ISSUE THREAD

**Issue by elamotte** [icebob/vue-form-generator#282]
I want, to replace the help tooltip behavior by a modal. I wonder what should be the best approach to do it properly, of course I could use vanilla js to modify DOM on render for each help icon, but I'm affraid it could be a bit heavy.
Anyone as found a good way to do something like that before?

**Comment by icebob** [comment]
Sorry, but currently there is no good way to change the template of vfg.

**Comment by elamotte** [comment]
Thanks for your answer, I finally made it with JQuery hook. Not perfect but in the meantime I prefer that and keep the possibility to update future versions of VFG.
