### ISSUE TITLE
Not changing language at the form

### ISSUE THREAD

**Issue by Kraska-8** [icebob/vue-form-generator#284]
Im using vue-i18n module to dynamically change language on the pages, but  text in generated form doesnt changed, only if I  refrech the page or go to other router page, how can I dynamically change text data in vue-form-generator?

**Comment by lionel-bijaoui** [comment]
I'm afraid there is no real solution yet.
My guess is that the reactivity is broken somewhere and vue-i18n render the translation as the string once.
I would like to improve i18n and validation in the next version of VFG but this is just wishful thinking for now.
Sorry, I can't help you.

**Comment by DelfsEngineering** [comment]
Could you not force a refresh of the schema, or re-add the reactivity via running it through a computed property or use cue.set as in here? [Vue reactivity](https://vuejs.org/v2/guide/list.html#Array-Change-Detection)

**Comment by icebob** [comment]
You can do it with VFG. Here is an example [fiddle](https://jsfiddle.net/icebob/de2yc74c/)

**Comment by lionel-bijaoui** [comment]
Yes, you can do it, but it is not compatible with vue-i18n API. Not a big problem, but I want to fix that.

**Comment by qkdreyer** [comment]
Any updates on this ?
