### ISSUE TITLE
no 'name' attribute?

### ISSUE THREAD

**Issue by sjsiegel001** [icebob/vue-form-generator#286]
it would be nice if there was a name attribute for each field

**Comment by DelfsEngineering** [comment]
You can add any additional keys to the `schema.fields` object. 
Then in your custom component reference it with `this.schema.myKey` 
What is your use case?

**Comment by sjsiegel001** [comment]
Thanks for the quick response. I'd like to submit the form traditionally without AJAX. Could you provide an example of this technique?

**Comment by sjsiegel001** [comment]
To anybody else interested, here's the solution I've come up with. It's definitely not ideal but it's a cute little jQuery fix:
`updated: function () {
            $('input').each(function(i, obj) {
                var inputid = $(this).attr('id');
                $('input').attr('name', inputid);
            });
        }`

**Comment by amoshydra** [comment]
This issue https://github.com/icebob/vue-form-generator/issues/78 seems to suggest that input field should come with a name attribute already. However, that's not the case in my testing.

**Comment by icebob** [comment]
You can set `name` attr with `inputName` prop in schema
https://github.com/icebob/vue-form-generator/blob/master/examples/post-form/main.js#L49
