### ISSUE TITLE
Vue warn:  The computed property "errors" is already defined in data

### ISSUE THREAD

**Issue by FranckFreiburger** [icebob/vue-form-generator#287]
Hi,
I get the following Vue warning when I test your [main example](https://github.com/icebob/vue-form-generator#usage):
 ` [Vue warn]: The computed property "errors" is already defined in data.`

(using Vue 2.4.2)

**Comment by DelfsEngineering** [comment]
If you have a computed property, you do not need to define it again in your data. The same goes for props.

**Comment by FranckFreiburger** [comment]
Thanks for the clue, `vee-validate` also defines `errors` .

**Comment by OgaBoss** [comment]
@FranckFreiburger, Please how did you resolve this ? Facing the same issue right now.

**Comment by FranckFreiburger** [comment]
I just removed my dependency to `vee-validate` that also defined an `errors` property.

**Comment by OgaBoss** [comment]
@FranckFreiburger so you mean it not possible to use `vee-validate` and `vue-form-generator` in the same project ?
