### ISSUE TITLE
<fieldset> breaking flexbox

### ISSUE THREAD

**Issue by joshdstockdale** [icebob/vue-form-generator#288]
I'm using a minimal flexbox grid for laying out my forms and <fieldset> is breaking it, as most browsers treat <fieldset> as a form input.

Can we do any of the following in the next release?
a) remove fieldset if legend is not specified
b) remove fieldset if not in groups
c) add an extra div inside fieldset to which we can assign a class

**Comment by ymoreiratiti** [comment]
Me Too

Using VueJS 2 with Webpack and bootstrap 4

**Comment by lionel-bijaoui** [comment]
You can already do better
```html
<vue-form-generator tag="div"><vue-form-generator>

```

**Comment by webdevnerdstuff** [comment]
Using version 2.1.1

I have tried adding tag="div" and it still is using fieldset.
