### ISSUE TITLE
there is language options?

### ISSUE THREAD

**Issue by Eder87rh** [icebob/vue-form-generator#289]
there is language options?

**Comment by akeyliu** [comment]
I found a solution to modify the vfp_core.js in dist directory.
You can just search and modify the error message with you want, i.e. Chinese Version.

**Comment by andy265** [comment]
You can overwrite variable "resources" (defined at /src/utils/validators.js).
Example of overwriting a "fieldIsRequired" message:

```
import VueFormGenerator from 'vue-form-generator'

VueFormGenerator.validators.resources.fieldIsRequired = 'My message'
```
