### ISSUE TITLE
How to add class to submit button ?

### ISSUE THREAD

**Issue by blendsoft** [icebob/vue-form-generator#294]
How to add class to submit button ?

**Comment by vuchl** [comment]
use the `styleClass`property in the schema: https://icebob.gitbooks.io/vueformgenerator/content/fields/field_properties.html

**Comment by blendsoft** [comment]
It adds to .form-group, not button.

**Comment by vuchl** [comment]
You are correc. and from looking at the code there is no way to bind classes to any of the fields.

**Comment by vuchl** [comment]
Maybe #295 will be merged and solves your issue. you now can specify the `classes` array in the `schema` .
