### ISSUE TITLE
multiselect field error after 'New'

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#30]
@lionel-bijaoui could you check this problem?

Reproduction:
1. `npm run dev`
2. Press `New` button
3. check console messages. It has 4 error messages, and fieldVueMultiSelect dropdown is empty.
![image](https://cloud.githubusercontent.com/assets/306521/17531562/b05a1b12-5e7c-11e6-9ba6-6523a1ad9b05.png)

**Comment by lionel-bijaoui** [comment]
I going to check this today.

**Comment by icebob** [comment]
Thank you!

**Comment by lionel-bijaoui** [comment]
Ok so vue-multiselect don't like to have an undefined value and crash.

**Comment by icebob** [comment]
So is it a multiselect bug? Are we report it?

**Comment by lionel-bijaoui** [comment]
I'm raising an issue right now

**Comment by icebob** [comment]
Great! Thanks!

**Comment by lionel-bijaoui** [comment]
https://github.com/monterail/vue-multiselect/issues/80

**Comment by icebob** [comment]
https://github.com/monterail/vue-multiselect/issues/88#issuecomment-246210052

**Comment by lionel-bijaoui** [comment]
We have green light for this

**Comment by icebob** [comment]
Could you test it in dev?

**Comment by lionel-bijaoui** [comment]
Yes

**Comment by lionel-bijaoui** [comment]
@icebob I still have a problem. :disappointed: 
I have changed some information, clicked save, clicked another profile then clicked back to the original profile and the data where still here. I got no error message in the console.
But when I do new, same error message.

**Comment by icebob** [comment]
I dont think so rawgit cached.
We need to create a fiddle with this issue to monterail, no?

**Comment by lionel-bijaoui** [comment]
Well, they have fixed monterail/vue-multiselect#88 but not monterail/vue-multiselect#80

**Comment by icebob** [comment]
ohh, my mistake. Sorry.

**Comment by lionel-bijaoui** [comment]
No pb, I did the same mistake

**Comment by icebob** [comment]
This problem is alive. I tested. I created a fiddle for developer of multiselect.

https://jsfiddle.net/icebob/0mg1v81e/174/

**Comment by lionel-bijaoui** [comment]
They don't like to have an `undefined` or `null` value. Maybe we could prevent it ?

**Comment by icebob** [comment]
But on the website in the "Basic Usage", he uses `value: null`

**Comment by icebob** [comment]
Fixed in 2.0.0-beta15
