### ISSUE TITLE
Enhancement: Add new field property - conditions

### ISSUE THREAD

**Issue by ramiy** [icebob/vue-form-generator#302]
The `conditions` property should control the field visibility. The field will be displayed only if the conditions are met.

Usage:

```javascript
"fields": [
	{
		type: "switch",
		label: "Some field",
		textOn: "Yes",
		textOff: "No",
		multi: true,
		default: false,
		model: "some_field"
	}, {
		type: "input",
		inputType: "text",
		label: "Dependent field",
		model: "dependent_field",
		"conditions": [
			{
				"field": "some_field",
				"compare": "===",   // ===, !==, >, <, >=, ......
				"value": true,
				"display": "show"   // show, hide, disable, readonly
			}
		]
	}
]
```

In this example, the second field will be displayed only if the first field equals true.

**Comment by icebob** [comment]
You can do it with `visible(model) { ... }`

**Comment by DelfsEngineering** [comment]
I think that idea is far too complicated an limiting. Instead replace the attribute value you want to control  `visible, readOnly ...` with a `function` that evaluates the truthiness of the condition. Then it can control anything.
