### ISSUE TITLE
No docs folder

### ISSUE THREAD

**Issue by RIanDeLaCruz** [icebob/vue-form-generator#304]
Hi @icebob 

I was wondering where the documentation is? Was going to make a PR to add documentation on some components but I couldn't seem to find where the docs reside
Thanks

**Comment by icebob** [comment]
The docs is on gitbook.

https://icebob.gitbooks.io/vueformgenerator/content/

You can login to gitbook make changes & create PRs, same as on github.

**Comment by RIanDeLaCruz** [comment]
Thanks!
