### ISSUE TITLE
Quasar framework support

### ISSUE THREAD

**Issue by Zyles** [icebob/vue-form-generator#306]
Would be sweet if this could be made compatible with the Quasar framework to render its components.

Right now it spits them out with no style if I include it.

**Comment by icebob** [comment]
Could you show a screenshot?

**Comment by Zyles** [comment]
Quasar uses unique components like `<q-input>` so you would need to map or provide a wrapper I think.

![form](https://user-images.githubusercontent.com/1741593/31446046-d96a72e4-ae9f-11e7-86ae-9ea2ddb7db26.png)

**Comment by icebob** [comment]
In this case I think vfg won't work with Quasar. Just if you create custom fields which uses the `q-` components.
