### ISSUE TITLE
Is there a office way to import jquery etc. for vue-form-generator

### ISSUE THREAD

**Issue by huoxudong125** [icebob/vue-form-generator#307]
I want to use rangeSlider  components ,but it depend on third libraries .  Is there a graceful(office) way  to import the other library. 

can use the way to import the jquery?
```
npm install jquery --save-dev
```

and how import into the vue file as local compment.
Many thanks for you!

**Comment by icebob** [comment]
I think you can use the following solution:
```js
import jQuery from "jquery";
window.$ = window.jQuery = jQuery;
```
