### ISSUE TITLE
Creating custom fields require formatValueToModel method

### ISSUE THREAD

**Issue by Alex-Sokolov** [icebob/vue-form-generator#308]
Creating custom fields require `formatValueToModel` method.
If no method there is a console error.
Maybe if no method available just use value? Now needed to add:
```js
formatValueToModel(value) {
  return value;
}
```

**Comment by icebob** [comment]
Released in [v2.1.1](https://github.com/icebob/vue-form-generator/releases/tag/v2.1.1)
