### ISSUE TITLE
Add independent vanilla field components

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#31]
Create fields with vanilla libs which have no jQuery and Bootstrap dependencies.

- [X] Select field -> [vue-multiselect](https://github.com/monterail/vue-multiselect)
- [x] DateTime field -> [Pikaday](https://github.com/dbushell/Pikaday)
- [x] Masked input field -> [VanillaMasker](https://github.com/BankFacil/vanilla-masker) or [cleave.js](https://github.com/nosir/cleave.js)
- [x] Slider field -> [noUiSlider](https://github.com/leongersen/noUiSlider)

For these developments I created an `independent` branch. Every PR needs to add to this branch.

https://github.com/icebob/vue-form-generator/tree/independent

**Comment by lionel-bijaoui** [comment]
noUiSlider is almost ready.
By default, noUiSlider return a float so I need a way to check if `validators.integer` is activated so I can `parseInt` the value if necessary.

**Comment by lionel-bijaoui** [comment]
I will go with cleave.js, the API is much easier to work with and it is way more popular.

**Comment by icebob** [comment]
Great!

**Comment by icebob** [comment]
@lionel-bijaoui in the next 7 days I will on holiday, so my response will be longer, but I will check your commits as soon as possible :+1:

**Comment by lionel-bijaoui** [comment]
That's perfect, I'm going on holiday too :)
I hope to do a PR for cleave and pikaday before the end of the day (just to initiate your feedback on them, I need some help).
Have a nice holiday !

**Comment by icebob** [comment]
@lionel-bijaoui Thanks! You have a nice holiday too!

**Comment by icebob** [comment]
@lionel-bijaoui I merged your fields. Fix lint errors and fix issues what I commented in your PR. So please rebase your fork.

**Comment by lionel-bijaoui** [comment]
Thank you, I was about to start working on this. Hope you had a great
holiday.

**Comment by lionel-bijaoui** [comment]
@icebob should I destroy my branches ?

**Comment by icebob** [comment]
Yes, if you want.

**Comment by icebob** [comment]
I will merge this `independent` branch to master

**Comment by lionel-bijaoui** [comment]
So soon ? Don't we need the unit test and all ?

**Comment by icebob** [comment]
This merge doesn't mean it will be a release :)
And need some tests for other fields too #40

**Comment by icebob** [comment]
Merged with #42
