### ISSUE TITLE
How to destroy/clear/reset form validation?

### ISSUE THREAD

**Issue by webdevnerdstuff** [icebob/vue-form-generator#325]
How do you reset the form validation and/or please add a way to destroy/clear/reset the validation on the form so left over errors are removed.

**For example**
Say you have a form module for _user_ and this form handles both "edit user" and "add user".

If you edit a user and cause a validation error, the error message shows up. You then close the module and then go to "add user", this results in the error message on the field to still be there.

**Edit Work Around**
The same problem happens if you were to edit another user, but I have at least found a work around for that. Technically the form is valid and there are no errors, but the error message is still there.  For that when the "edit user" module is opened back up I call a method:

`this.validateDecision();`

In that method I have

`return this.$refs.userForm.validate();`

This isn't perfect, but it at least sort of works. It's a little hacky though and a better solution would be preferable.

**Result Wanted**
It would be nice if there was a way to just destroy/clear/reset once a module is closed, or at least some option with vue-form-generator to have this. So when there is an error on one form, when you open up the form again for another edit or add there are no errors on the form.

Perhaps having another "formOptions" would be nice, as well as a validate on field leave, not just after change.

**Comment by webdevnerdstuff** [comment]
Looks like this does the trick.

`this.$refs.userForm.clearValidationErrors();`

**Comment by shah-dhaval** [comment]
@webdevnerdstuff  Can you please share how you have achieved form reset?

**Comment by webdevnerdstuff** [comment]
Please see my previous comments, the solution is there.
