### ISSUE TITLE
new field: google address autocomplete

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#33]
Github: https://github.com/gocanto/google-autocomplete
Demo: https://gocanto.github.io/google-autocomplete/

![Demo](https://github.com/gocanto/google-autocomplete/raw/master/src/images/example.gif)

**Comment by lionel-bijaoui** [comment]
This lib is not available as a simple js file. It seem like it will need to be added to the devDependency, no ?

**Comment by icebob** [comment]
This is not a big lib. ~150 lines. So I think it will be a "built-in" field.

https://gist.github.com/gocanto/0a99d0d9f3e0a15594c272887b07c8d1
