### ISSUE TITLE
How to create linked fields?

### ISSUE THREAD

**Issue by blackfyre** [icebob/vue-form-generator#43]
I would like to create two select fields which affect each other, basically the possible values should change depending on the other field.
Is there a way to do this?

I've read the documentation on the field's general `onChanged` property but I could not figure out a way to access the schema.

**Comment by icebob** [comment]
Yes. If you are using select fields, you need to add function as the `values` property instead of array. In this function you got the model and schema objects.

Example fiddle: https://jsfiddle.net/6xh0e3nx/1/

**Comment by icebob** [comment]
Btw you can use functions for `visible` and `disabled` properties too. See also: https://github.com/icebob/vue-form-generator/issues/35#issuecomment-239280977

**Comment by blackfyre** [comment]
Wonderful! Thank you!
Maybe you could add this to the documentation?

**Comment by icebob** [comment]
Yes, I will add.

**Comment by gezichenshan** [comment]
Is there any way to init the select values in ajax?

**Comment by gezichenshan** [comment]
OK,I see.I have done by this way.
```
{
            type: "select",
            label: "A",
            model: "loanType",
            values: function(model, schema){
              let loanTypeArr = Object.keys(model.loanTypeObj)
              return loanTypeArr
            },
            required: true,
          },
          {
            type: "select",
            label: "B",
            model: "loanDestination",
            values: function(model, schema) {
							switch(model.loanType) {
								case "xxx": return model.loanTypeObj['Adquisición de activo fijo o equipamiento'];
								case "yyy": return model.loanTypeObj['Capital de trabajo'];
							}
							return [];
						},
methods: {
    getConfig() {
      getConfig().then((result) => {
        this.model.loanTypeObj = result.data.loanType
      })
    },
  },
created() {
    this.getConfig()
  }
```
