### ISSUE TITLE
create native HTML5 fields

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#50]
Because currently there is no vanilla datetime picker. Pickaday is only date selector.

- [x] create new field common type which has a "inputType" property. (break changes)
- [x] rename `datetime` field to `datetimePicker` (break changes)
- [x] rename `slider` field to `rangeSlider` (break changes)
- [x] update docs (add new radio values description)

Available types
- [x] date
- [x] datetime
- [x] datetime-local
- [x] time
- [x] month
- [x] week

Other HTML5 types
- [x] url
- [x] tel
- [x] radio

Set this inputType to the field type attributes:
```jade
input( :type="schema.inputType")
```

**Comment by lionel-bijaoui** [comment]
Same thing should be done with slider field. It should be renamed "ion.rangeSlider" or "rangeSlider".
Also a "radio" field ! Switch is cool, but sometime you need more the 2 values.
And "tel" for a native masked/cleave for phone number only.
Last one is "url".
I would also like to point out that we need more HTML5 attributes:
- autofocus
- inputmode
- selectionDirection
- spellcheck

specific to text, search, tel, url or email:
- pattern
- size (also for password)

:boom: *More HTML5!* :boom:

**Comment by icebob** [comment]
HTML5 range is exist as `fieldRange`. I added the other types to the tasklist.

what is the `size` attr?

**Comment by lionel-bijaoui** [comment]
Yeah, sorry I forgot to remove that sentence.

> **size**
The initial size of the control. This value is in pixels unless the value of the type attribute is text or password, in which case, it is an integer number of characters. Starting in HTML5, this attribute applies only when the type attribute is set to text, search, tel, url, email, or password; otherwise it is ignored. In addition, the size must be greater than zero. If you don't specify a size, a default value of 20 is used. HTML5 simply states "the user agent should ensure that at least that many characters are visible", but different characters can have different widths in certains fonts; in some browsers, a certain string with x characters will not be entirely visible even if size is defined to at least x.

[Source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input)

I think the goal for v1.0.0 is to have all attributes exposed for native HTML5 fields.

**Comment by icebob** [comment]
I think, the source is not neccessary, because the default `width` is 100%. So it is overwrite the `size` attr.
And you can change this width via `styleClasses` property in schema

**Comment by lionel-bijaoui** [comment]
Yes, but if you change the width via styleClasses and then, you may want to use it for some reason. I mean, it don't cost much to add, why not add it just in case someone needs it ?

**Comment by lionel-bijaoui** [comment]
@icebob We need a `radio` field, right ?

**Comment by icebob** [comment]
Yes, I added to the list.

**Comment by lionel-bijaoui** [comment]
I'm going to work on a html5 field based on `input( :type="schema.inputType")`
One field for all native `input`.
Check the html5 branch on the doc.

**Comment by icebob** [comment]
good solution, thanks!

**Comment by icebob** [comment]
I'm unsure with the `inputType` property. Currently easy and straightforward to create a simple text field in the schema:
```js
{
  type: "text",
  label: "Name",
  model: "name"
}
```

but after this feature, it will be more complex and harder to read:
```js
{
  type: "html5",
  inputType: "text",
  label: "Name",
  model: "name"
}
```

So I think would be good to stay the current format. But need to rewrite the `getFieldType` part: https://github.com/icebob/vue-form-generator/blob/master/src/formGenerator.vue#L108

It would be smarter. So it will try to search the field by the exact name (`fieldText`). If not found use the common `html5` field and set the `type` to `inputType`.

**Comment by lionel-bijaoui** [comment]
I have a counter arguments: putting them under the  "html5" umbrella avoid collision with other potential field name, especially since custom fields exist.
It also simplify the documentation. HTML are well documented already, not need to explicitly redo it for each field. We only provide a shell for them and potentially *future* new HTML field.
Also most other fields use special properties already and it is not a big problem.

**Comment by lionel-bijaoui** [comment]
@icebob I have edited my answer, I really hope I was able to convince you :smile:. I will soon do a PR (still need test) with my proposal, but it will use a new feature of github which allow you to modify directly my PR if you need to.

**Comment by icebob** [comment]
> I welcomed this new github feature. I think it is neccessary for contribution.

1. I don't want to reject my thoughts about searching, because it will affect only one function. I will try it.
2. My other confusion is the `html5` type (Now I see you wrote it too). I think we need to change this field type to `input` instead of `html5`

**Comment by lionel-bijaoui** [comment]
Ok since #70 is done, what's left is: 
- a `radio` thing
- rename datetime field to datetimePicker (break changes)
- rename slider field to rangeSlider (break changes)
I'm going to start with the renaming, since it is fast and easy

**Comment by icebob** [comment]
Great!

**Comment by lionel-bijaoui** [comment]
Ok, now are left `radio` thing and docs work.
@icebob Do you think you could give me a little help with the doc ? or you don't have free time ?
I understand if you don't have free time, this information will simply help me evaluate the time needed.

**Comment by icebob** [comment]
Nice! Thank you.
Sorry, but currently I can't help, because I have a lot of work in my full-time job :(
I hope one week and I will be more active with VFG :smile:

**Comment by lionel-bijaoui** [comment]
No pb, I understand. Maybe you could add me as a [collaborator](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/) ? If you don't feel like it, I perfectly understand, this is your project and you have complete control over it.

--
I'm going to create a "radio**_s_**" field ;)
It will be close to "checklist" in a way, but sometime, you really need `radio` inputs.

**Comment by icebob** [comment]
A while ago, I'm thinking that I add you as a collaborator. Because you have a lot of hard work to improve this component, what I thank you. 
But I want to controlling the direction of development. So I will add you, but I will need to approve the PRs before merge, that I can check the changes, ok?

**Comment by lionel-bijaoui** [comment]
No problem, I would not like to push thing without your validation anyway :)
I'm mainly going to use the kanboard and tag issues

**Comment by icebob** [comment]
@lionel-bijaoui Are you working anything from this issue?

**Comment by lionel-bijaoui** [comment]
Yes, I'm on the "radios" field. I can do a PR tomorrow if you want to help (I very busy at work lately).
You could do the docs if you can.

**Comment by icebob** [comment]
Ok, I updated docs in html5 branch.

**Comment by lionel-bijaoui** [comment]
@icebob #80 I do the unit test and it's done

**Comment by lionel-bijaoui** [comment]
@icebob I'm done with the doc !

**Comment by icebob** [comment]
Thanks! Tomorrow I will make the new release
