### ISSUE TITLE
Missing callback for pikaday field

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#53]
While doing the documentation for pikaday field, I noticed that the following callback are not available.
- onSelect: callback function for when a date is selected
- onOpen: callback function for when the picker becomes visible
- onClose: callback function for when the picker is hidden
- onDraw: callback function for when the picker draws a new month

They should be added, no ?

**Comment by icebob** [comment]
I think currently we don't need this callbacks. Only changes, but it triggered by field.
