### ISSUE TITLE
Add default values to the documentation

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#55]
Fields description should have a "default" column.
Concerned fields:
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/field_properties.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/inside_buttons.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/checklist.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/email.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/image.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/number.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/password.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/range.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/submit.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/select.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/switch.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/text.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/textarea.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/datetime.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/masked.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/selectex.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/slider.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/spectrum.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/googleaddress.md
- [x] https://www.gitbook.com/book/icebob/vueformgenerator/edit#/edit/master/fields/vuemultiselect.md

**Comment by icebob** [comment]
Awesome
