### ISSUE TITLE
Fragment instance (again :( )

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#57]
I'm using vfg in another project with webpack. And vfg is marked as a fragment instance. I don't get it...
Same Vue version as the one use in the dev example.

**Comment by icebob** [comment]
Could you show the template code?

**Comment by lionel-bijaoui** [comment]
I tested the new version it in another project and no problem there. I will try to pinpoint the exact problem.

**Comment by icebob** [comment]
Weird :confused:

**Comment by lionel-bijaoui** [comment]
Ok, I found the problem and it is dumb.
I imported the components in a 'normal' way:
```js
components: {
    VueFormGenerator
}
```
And this is not how it work for this plugin. The correct way:
```js
components: {
    VueFormGenerator: VueFormGenerator.component
}
```
I'm looking at a way to make it behave like normal components

**Comment by icebob** [comment]
The reason is that library contains validators and schema util functions too.
https://github.com/icebob/vue-form-generator/blob/master/src/index.js#L2

So you need to add as 
```js
components: {
    VueFormGenerator: VueFormGenerator.component
}
```

or register globally when your app start
```js
Vue.use(VueFormGenerator);
```
