### ISSUE TITLE
What is `help` is supposed to do ?

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#61]
I don't get it, nothing seem to change when I use the option.

> show this help if mouse hover the question icon before the caption of field. *You can use HTML elements too.*

What question mark ? How do I use HTML elements ?
Thank you for your help.

**Comment by icebob** [comment]
Check the phone field in dev:
![image](https://cloud.githubusercontent.com/assets/306521/18177134/1569a4ec-7079-11e6-964b-fd570b116fea.png)

**Comment by lionel-bijaoui** [comment]
Ok I tested, Font Awesome is required for something to appear.
Can we do something about it (like we did with bootstrap) ?
It is only a small icon, maybe we could convert it to base64 and include it in the CSS ?

**Comment by icebob** [comment]
Yes, we need to change it to this as inline img: https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/16/question-circle.png

**Comment by lionel-bijaoui** [comment]
base64
> data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA+UlEQVQ4ja3TS0oDQRAG4C8+lq7ceICICoLGK7iXuNBbeAMJuPVOIm7cqmDiIncIggg+cMZFaqCnZyYKWtB0df31V1VXdfNH6S2wD9CP8xT3KH8T9BiTcE7XBMOfyBcogvCFO9ziLWwFRosyV+QxthNsA9dJkEYlvazsQdi3sBv6Ol6TBLX+HWT3fcQZ3vGM5fBLk+ynAU41m1biCXvhs4OPBDuBpa6GxF0P8YAj3GA1d1qJfdoS4DOIcIm1DK9x8iaWeDF/SP3QU6zRROpjLDFLsFlibx1jJaMkSIGrWKntvItcyTBKzCcybsvc9ZmYz3kz9Ooz/b98A8yvW13B3ch6AAAAAElFTkSuQmCC

css background
> url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA+UlEQVQ4ja3TS0oDQRAG4C8+lq7ceICICoLGK7iXuNBbeAMJuPVOIm7cqmDiIncIggg+cMZFaqCnZyYKWtB0df31V1VXdfNH6S2wD9CP8xT3KH8T9BiTcE7XBMOfyBcogvCFO9ziLWwFRosyV+QxthNsA9dJkEYlvazsQdi3sBv6Ol6TBLX+HWT3fcQZ3vGM5fBLk+ynAU41m1biCXvhs4OPBDuBpa6GxF0P8YAj3GA1d1qJfdoS4DOIcIm1DK9x8iaWeDF/SP3QU6zRROpjLDFLsFlibx1jJaMkSIGrWKntvItcyTBKzCcybsvc9ZmYz3kz9Ooz/b98A8yvW13B3ch6AAAAAElFTkSuQmCC')

**Comment by icebob** [comment]
Done
