### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#62]
In the doc, it say that custom fields are "coming soon". It is something very interesting.

Can you share your progress on that feature ?
Can I help you on that ?

**Comment by icebob** [comment]
Need to create an example on webpackbin. Just webpackbin is not working properly.

The idea:

You create a custom field component. E.g.: `fieldAwesome`. And if you register this component globally with `Vue.component("fieldAwesome", FieldAwesome);` than you can use it in your schema like:
```js
{
	type: "awesome",
	label: "My aweseom field",
	model: "awesome"
}
```

**Comment by icebob** [comment]
#65 
It's working, just needed a reference to `abstractField` for mixins
