### ISSUE TITLE
Checklist field don't have a working disabled attribute

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#66]
I was checking attributes in the doc and unit test when I realized that.

**Comment by icebob** [comment]
Thanks, I will fix it.

**Comment by lionel-bijaoui** [comment]
I have a working fix too

**Comment by icebob** [comment]
Ohh, great!

**Comment by lionel-bijaoui** [comment]
I will add it with the attribute PR #63
