### ISSUE TITLE
staticMap is limited to `lat` and `lng` properties to work

### ISSUE THREAD

**Issue by lionel-bijaoui** [icebob/vue-form-generator#68]
staticMap don't work in the dev example because geo data is defined with `latitude` and `longitude` properties.
Maybe it need a `staticMapOptions` with properties to map to the good value:
```js
{
	type: "staticMap",
	label: "Map",
	model: "address.geo",
	staticMapOptions: {
		lat: "latitude",
		lng: "longitude",
		sizeX:600,
		sizeY:300
	}
}
```
edit: size param too

**Comment by lionel-bijaoui** [comment]
I'm going to do a PR that add many parameters and fix the issue

**Comment by icebob** [comment]
Good solution. Thanks!
