### ISSUE TITLE
Add `name` attr to input, select, textarea fields

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#78]
Because with it, we can generate native submittable form too. With submit button, this `named` fields can be send to server side with POST. [Spec](http://www.w3schools.com/tags/att_input_name.asp)
- [x] add `name` attributes from `schema.inputName` property to `input`, `select`, `textarea` fields
- [x] create example. POST data to https://httpbin.org/post 
- [x] cover with tests
- [x] update docs

**Comment by icebob** [comment]
Development in `form_name_attr` [branch](https://github.com/icebob/vue-form-generator/tree/form_name_attr)

**Comment by lionel-bijaoui** [comment]
It seems a bit too much work for 0.5.0, why not for another milestone (0.6.0) ? I really need to use this version in the coming weeks.

**Comment by icebob** [comment]
Merged with #86

**Comment by icebob** [comment]
Released
