### ISSUE TITLE
update deps

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#79]

**Comment by lionel-bijaoui** [comment]
What dependency you want to update ?

**Comment by icebob** [comment]
The npm packages

**Comment by lionel-bijaoui** [comment]
Yes, I understand that, but what package ?

**Comment by icebob** [comment]
![image](https://cloud.githubusercontent.com/assets/306521/18882314/fb92bd54-84de-11e6-9228-27e88d7ce8db.png)

**Comment by lionel-bijaoui** [comment]
How did you get this list, it's awesome !

**Comment by icebob** [comment]
I use [npm-check](https://github.com/dylang/npm-check) to update deps. Very easy

**Comment by icebob** [comment]
:tada:  New version released: https://github.com/icebob/vue-form-generator/releases/tag/v0.5.0
