### ISSUE TITLE
<Not selected> text extract to schema properties (i18n)

### ISSUE THREAD

**Issue by Cannonb4ll** [icebob/vue-form-generator#82]
When I create a select box, it will put this inside it:

![Image](http://screenshot.serverbuilds.nl/0o2T2L3Q3H11/Image%202016-09-28%20at%206.23.42%20PM.png)

`<Not selected>`

Why is this exactly? I would like it to see that it will add my placeholder to the element. Also, languagewise this is conflicting with me, I am dutch and thus anther language would be nice. (Maybe optional when adding such a field)

**Comment by icebob** [comment]
Thanks, we will fix it.

**Comment by Cannonb4ll** [comment]
Great work anyway, it is a really good package! 💃

**Comment by icebob** [comment]
Fixed. Will be released in v0.6.0
