### ISSUE TITLE
Try text-mask as a vanilla input mask field

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#83]
https://github.com/text-mask/text-mask

**Comment by lionel-bijaoui** [comment]
I've already looked into it and I prefer Cleave.  
Text Mask have 2 interesting options (`guide` and `keepCharPositions`) but does not provide easy default masking scenario.  
Cleave can identify credit card type and provide callback for that for example. They also have a library for phone number by country. Etc.
