### ISSUE TITLE
multiselect: put back custom-label & fix

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#87]
I [removed](https://github.com/icebob/vue-form-generator/commit/5dfc5bb866e8c713ab89be92c62a4645f7c765b4) `custom-label` property from multiselect because give errors.
If it props doesn't exist in schema, multiselect try to call and gives error.

**Comment by lionel-bijaoui** [comment]
I had the same problem while working the v2, and found a solution. It need to at least (even when empty) return a function. I was returning `null` and it was not happy.
I will update my master and do a PR with the fix.

**Comment by icebob** [comment]
Merged. Thanks!
