### ISSUE TITLE
Failed to compile template

### ISSUE THREAD

**Issue by jmaister** [icebob/vue-form-generator#95]
> [Vue warn]: failed to compile template:
> 
> <div><fieldset v-if="schema != null" class=vue-form-generator><template v-for="field in fields"><div v-if=fieldVisible(field) :class=getFieldRowClasses(field) class=form-group><label>{{ field.label }}<span v-if=field.help class=help><i class=icon></i><div class=helpText>{{{field.help}}}</div></span></label><div class=field-wrap><component :is=getFieldType(field) :disabled=fieldDisabled(field) :model.sync=model :schema.sync=field></component><div v-if="field.buttons &amp;&amp; field.buttons.length &gt; 0" class=buttons><button v-for="btn in field.buttons" @click="btn.onclick(model, field)" :class=btn.classes>{{ btn.label }}</button></div></div><div v-if=field.hint class=hint>{{ field.hint }}</div><div v-if="field.errors &amp;&amp; field.errors.length &gt; 0" class=errors><span v-for="error in field.errors" track-by=$index>{{ error }}</span></div></div></template></fieldset></div>
> 
> - invalid expression: {{{field.help}}}
> 
>  
> (found in component <vue-form-generator>)

**Comment by icebob** [comment]
Are you trying to use with Vue 2.x?

**Comment by jmaister** [comment]
Yes, I am using Vue 2.0.5.

I just found that running with Vue 1.x works perfectly.

**Comment by icebob** [comment]
Yes, we are working on Vue v2.x support #89

**Comment by markuman** [comment]
I got the same error, but also with 0.6.1 (installed with `npm install vue-form-generator --save`)

    $ npm list|grep form-generator
    ├─┬ vue-form-generator@0.6.1
 


        [Vue warn]: Error compiling template:

        <div><fieldset v-if="schema != null" class=vue-form-generator><template v-for="field in fields"><div v-if=fieldVisible(field) :class=getFieldRowClasses(field) class=form-group><label>{{ field.label }}<span v-if=field.help class=help><i class=icon></i><div class=helpText>{{{field.help}}}</div></span></label><div class=field-wrap><component :is=getFieldType(field) :disabled=fieldDisabled(field) :model.sync=model :schema.sync=field></component><div v-if="field.buttons &amp;&amp; field.buttons.length &gt; 0" class=buttons><button v-for="btn in field.buttons" @click="btn.onclick(model, field)" :class=btn.classes>{{ btn.label }}</button></div></div><div v-if=field.hint class=hint>{{ field.hint }}</div><div v-if="field.errors &amp;&amp; field.errors.length &gt; 0" class=errors><span v-for="error in field.errors" track-by=$index>{{ error }}</span></div></div></template></fieldset></div>

        - invalid expression: {{{field.help}}}
         
        (found in <VueFormGenerator>)


any ideas?

**Comment by icebob** [comment]
The v0.6.1 is for only vue 1.x
For Vue 2.x use the latest v2.0.0-beta release
