### ISSUE TITLE
Error installing version 0.6.0 with bower

### ISSUE THREAD

**Issue by jmaister** [icebob/vue-form-generator#98]
Error message:

    E:\temp\test>bower install vue-form-generator
    bower not-cached    https://github.com/icebob/vue-form-generator.git#*
    bower resolve       https://github.com/icebob/vue-form-generator.git#*
    bower download      https://github.com/icebob/vue-form-generator/archive/v0.6.0.tar.gz
    bower extract       vue-form-generator#* archive.tar.gz
    bower EMALFORMED    Failed to read C:\Users\XXX\AppData\Local\Temp\XXX\bower\d143818c4d979cc4ccc84db10e66f35d-6332-hRFidN\bower.json

    Additional error details:
    Unexpected token ] in JSON at position 305

**Comment by icebob** [comment]
Thanks. The bug fixed. Tomorrow I will make a new patch release with fix.
